### ISSUE TITLE
Data Loader for Mac M2

### ISSUE THREAD

**Issue by victorng8** [forcedotcom/dataloader#641] opened 2023-04-02 06:36 UTC
**Describe the bug**
Not able to open Dataloader

**To Reproduce**
I followed the guide on this https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/loader_install_mac.htm

I did all the 8 steps listed successfully on that link with the additional steps for "Running Data Loader on Mac M1 Hardware"
To run Data Loader on Mac M1 hardware:

1) Open Terminal and run the command:
  /usr/sbin/softwareupdate --install-rosetta
2) Make sure you have Java Runtime Environment (JRE) version 11 or later, such as Zulu OpenJDK version 11 or later [for macOS](https://www.azul.com/downloads/?os=macos&package=jdk) x86 64-bit architecture installed on your Mac M1. Native JRE for ARM architecture doesn’t work in this scenario.
3) Run the installer.command file from the Data Loader folder that you downloaded. For details about this step, see the procedure at the top of this page.

**Expected behavior**
For Dataloader to open

**Screenshots**

**Desktop (please complete the following information):**
Apple M2
macOS Ventura Version 13.2.1 (22D68)

**Comment by ashitsalesforce** [comment] 2023-04-02 15:39
Hi @victorng8 , which version of data loader have you downloaded? Go to data loader installation folder using Finder. The default installation folder is ${HOME}/dataloader/v<data loader version>. Double-click dataloader_console. It will launch data loader with open terminal window. Capture the output on the terminal and share it so that we can further troubleshoot the issue.

**Comment by victorng8** [comment] 2023-04-02 15:55
57.0.1

**Comment by ashitsalesforce** [comment] 2023-04-02 15:57
Thanks. Share output of `dataloader_console` for further troubleshooting.

**Comment by ashitsalesforce** [comment] 2023-04-14 17:04
Closing assuming that the issue is resolved.

**Closed by ashitsalesforce** 2023-04-14 17:04 UTC

**Comment by victorng8** [comment] 2023-04-16 05:49
Sorry. Meant to reply but forgot. 
I couldn't achieve using the point and click way so I opened terminal and did :

`java -jar target/dataloader-x.y.z-uber.jar` which opened it!

But when I try login via the OAuth way I was getting an error 
"Error : Check your username and password. If you still can't login, contact your Salesforce" 

**Terminal Stack Trace below :**
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2023-04-16 13:45:53,588 INFO  [main] controller.Controller _doInitializeLog (Controller.java:402) - The log has been initialized
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2023-04-16 13:45:58,835 INFO  [main] controller.Controller _doInitializeLog (Controller.java:402) - The log has been initialized
2023-04-16 13:45:58,837 INFO  [main] config.Config createDir (Config.java:1470) - Config directory already exists: /Users/xxx/Downloads/dataloader_mac_v57.0.1/configs
2023-04-16 13:45:58,837 INFO  [main] config.Config getInstance (Config.java:1499) - Looking for file in config path: /Users/xxx/Downloads/dataloader_mac_v57.0.1/configs/config.properties
2023-04-16 13:45:58,837 INFO  [main] config.Config getInstance (Config.java:1525) - User config is found in /Users/xxx/Downloads/dataloader_mac_v57.0.1/configs/config.properties
2023-04-16 13:45:58,874 INFO  [main] config.LastRun load (LastRun.java:87) - Last run info will be saved in file: /Users/xxx/Downloads/dataloader_mac_v57.0.1/configs/ui_lastRun.properties
2023-04-16 13:45:58,874 INFO  [main] config.Config getInstance (Config.java:1531) - The controller config has been initialized
2023-04-16 13:46:05,022 INFO  [main] action.OperationInfoUIHelper instantiateWizard (OperationInfoUIHelper.java:111) - !OperationInfoUIHelper.creatingWizard!
2023-04-16 13:46:12,340 ERROR [main] ui.OAuthLoginFromBrowserFlow open (OAuthLoginFromBrowserFlow.java:78) - PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by ashitsalesforce** [comment] 2023-04-16 15:46
Hi @victorng8 ,

The last line in the log output is indicative of the problem.
```
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

It indicates that the server data loader is trying to connect to has self-signed certificates, which may be the case if you are going through a proxy. Alternately, your config.properties file may have an incorrect setting. Take the following steps so that we can troubleshoot the issue further.

Here are a couple of screenshots of data loader when I attempt a login. Can you share your screenshots?

<img width="570" alt="Screenshot 2023-04-16 at 8 41 44 AM" src="https://user-images.githubusercontent.com/71143047/232324198-0293469d-34df-4249-a08a-f782fd173b02.png">

<img width="595" alt="Screenshot 2023-04-16 at 8 41 24 AM" src="https://user-images.githubusercontent.com/71143047/232324211-2125f29c-7189-40e1-97bd-4f9765f95b37.png">
