### ISSUE TITLE
Dataloader v54 Provides Limited Output Information Compared to v49

### ISSUE THREAD

**Issue by Creamer2** [forcedotcom/dataloader#448] opened 2022-04-06 20:46 UTC
Currently using Dataloader v49 but attempting to upgrade to v54. Newer version v54 does not output the same information as v49. v54 output is missing number of errors or successes, config file info, login info, proxy info, port info, issues with empty columns, total record count, record rate per hour, estimated times, etc. Attached screenshots show CMD output screen from v49 and v54 using the same exact file on the same server.
![v49 CMD Run](https://user-images.githubusercontent.com/103147673/162067675-7ce88b42-69aa-4963-9f26-7d55b74ba3e0.png)
![v49 CMD Run 2](https://user-images.githubusercontent.com/103147673/162067673-7d3fcd29-bf1c-4bea-b1ae-0a96db448cdf.png)
![v54 CMD Run](https://user-images.githubusercontent.com/103147673/162067676-e3ef234c-ff79-49e7-9c67-e615f94bc97c.png)

**Comment by ashitsalesforce** [comment] 2022-04-07 01:11
Hi @Creamer2 , it is likely that either log-conf.xml is missing or `level` attribute of the `root` element in log-conf.xml is set to `error`. 

Is process-conf.xml for your v54 of data loader located in `E:\SHS_Customer_Contacts\` folder? If so, does that folder also contain log-conf.xml? If so, please provide its content so that we can troubleshoot the issue further.

**Comment by Creamer2** [comment] 2022-04-07 14:50
Hi @ashitsalesforce, in the log-conf.xml the level attribute of the root element is set to "info". The process-conf.xml is located in the samples folder.

![log-conf](https://user-images.githubusercontent.com/103147673/162227366-2419b596-a93a-4990-bed1-4eb97c1e98b8.png)
.

**Comment by Creamer2** [comment] 2022-04-07 18:56
@ashitsalesforce answers below:
- Full folder path of v54.0.0 process.bat file: C:\Program Files (x86)\salesforce.com\Apex Data Loader\bin
- v49 is not installed on the same desktop, it was previously installed in C:\Program Files (x86)\salesforce.com\Apex Data Loader
- Full folder path of process-conf.xml: C:\Program Files (x86)\salesforce.com\Apex Data Loader\samples\conf
- Full folder path of log-conf.xml: C:\Program Files (x86)\salesforce.com\Apex Data Loader\configs

**Comment by ashitsalesforce** [comment] 2022-04-07 19:26
Thanks @Creamer2 . How are you invoking process.bat in `C:\Program Files (x86)\salesforce.com\Apex Data Loader\bin`? Are you invoking it as `process ..\samples\conf <id of your process bean>` or something else?

**Comment by Creamer2** [comment] 2022-04-08 16:50
Hi @ashitsalesforce, We execute a batch file on our E: Drive which changes the drive and directory to C:\Program Files (x86)\salesforce.com\Apex Data Loader\bin. This is where the process.bat file is located. The batch file on the E: drive also contains the directories of all the config files we use for each different csv file.

**Comment by ashitsalesforce** [comment] 2022-04-08 17:49
Hi @Creamer2 , understood. Does `E:\SHS_Customer_Contacts\Config` contain log-conf.xml? If not, copy it from `C:\Program Files (x86)\salesforce.com\Apex Data Loader\samples` to `E:\SHS_Customer_Contacts\Config` and retry your batch script.

**Comment by Creamer2** [comment] 2022-04-11 16:29
Hi @ashitsalesforce, I followed your latest instructions and it worked! However, with this setup we would have to add the log-conf.xml to 67 different config folders. Do you know if there is a single directory we can move the log-conf.xml so that it works with all of our different configs?

**Comment by ashitsalesforce** [comment] 2022-04-11 16:40
Hi @Creamer2 , glad to hear that this approach worked. We have improved the code for the upcoming releases to extract log-conf.xml from the data loader jar and install it in config folder if not found. It is also available in the patch fix 54.0.2 - [dataloader_win.zip](https://github.com/forcedotcom/dataloader/files/8461376/dataloader_win.zip) - MD5: 95f122551ef1d99cb14733515a439a39.

Alternately, you can set LOG4J_CONFIGURATION_FILE environment variable to the absolute path of log-conf.xml to avoid copying.

**Comment by ashitsalesforce** [comment] 2022-04-12 20:25
closing as the issue is resolved.

**Closed by ashitsalesforce** 2022-04-12 20:25 UTC
