### ISSUE TITLE
Error while calling web service operation: upsert, error was: Failed to send request to ***.my.salesforce.com/services/Soap/u/54.0

### ISSUE THREAD

**Issue by turivid** [forcedotcom/dataloader#469] opened 2022-05-31 17:29 UTC
We are experiencing issues like this since the log4j fix.

Story:
We developed about 10 years ago a custom dataloader in deplhi using sfdc dataloader. (mostly for flexible input/data source transformations) We used the 35.0.0 version of dataloader until the log4j outbreak. We needed to change the base of our solution to 53.0.3.  Since that update we are struggling with several problems: mostly the creation of the final logs stopped working and become unstable. Sometime the dataloading is successful but the logs not creating at all. MOstly it happens with larger files (>10k lines) Recently I saw errors like this:  "ERROR com.salesforce.dataloader.client.PartnerClient - Error while calling web service operation: upsert, error was: Failed to send request to https://***.my.salesforce.com/services/Soap/u/53.0/***"

I thought the problem is in our part, in the good old deplhi core. But today I am facing with the followig error during using the official dataloader (54.0.0) too:

![image](https://user-images.githubusercontent.com/35538732/171234390-ab03d3f6-9ab7-4d6a-bf5e-86a79efcb797.png)

Could you please advise in this situation? Is this a known issue? I can provide the input file if it is needed

**Comment by ashitsalesforce** [comment] 2022-05-31 18:55
Hi @turivid , please provide the console output or the log when you see the error using data loader. Make sure to remove any personal or business-sensitive information before doing so. Alternately, file a support case with Salesforce Support to help resolve this issue.

**Comment by ashitsalesforce** [comment] 2022-05-31 20:27
Hi @turivid , also provide config.properties file after removing any personal or business-sensitive information.

**Comment by turivid** [comment] 2022-06-01 09:01
Hi @ashitsalesforce 
Thank you for your help

[error log.txt](https://github.com/forcedotcom/dataloader/files/8812660/error.log.txt)
[config_.properties.txt](https://github.com/forcedotcom/dataloader/files/8812684/config_.properties.txt)

**Comment by turivid** [comment] 2022-06-01 11:20
I tried to reduce the source file and now I am getting this: check the total/success+error record counter
![image](https://user-images.githubusercontent.com/35538732/171392596-c3f82324-d528-4362-a99a-31779685779e.png)

**Comment by ashitsalesforce** [comment] 2022-06-01 16:04
Hi @turivid , here are a couple of observations regarding your config.properties that result in the issues you are seeing:

1. The property `process.loadRowToStartAt=13876` means first 13,876 rows of your csv are ignored. Given that your reduced csv file has 18,029 records and 13,876 are skipped, 4,153 rows should have been processed. The code processes 3,808 rows instead and stops for some reason, perhaps due to the "failed to send request to <your org's my URL>" error, likely caused by `sfdc.loadBatchSize=1` (default for partner API is `sfdc.loadBatchSize=200`).

2. You are using partner API for your operation. Given the size of the load, I suggest trying bulk API instead by setting `sfdc.useBulkApi=true` and `sfdc.loadBatchSize=2000` (default for Bulk API) instead of `sfdc.loadBatchSize=1` in your config.properties and retry.

**Comment by ashitsalesforce** [comment] 2022-06-02 16:45
Hi @turivid ,

Good to hear that the mystery of why a lot fewer than expected rows getting processed is solved.

Regarding sfdc.loadBatchSize=1  usage, that seems to be the right thing to do for your upserts if dedup is not possible before executing data loader in batch mode. As to why you get error with duplicate external ids if batch size > 1, it is working as intended. Here is the knowledge article - https://help.salesforce.com/s/articleView?id=000323361&type=1.

Rationale for such behavior: with batch size > 1, multiple records are created and/or updated in a single server-side transaction. The order in which they are created/updated is not the same as the order specified by the client, in this case data loader, which uses the same order as the rows in the CSV file. Consequently, the server cannot guarantee that the field values specified in the last occurrence of a record with a specific external id are saved and therefore returns an error instead of creating or updating the record with multiple occurrences of an external id in a batch in an upsert operation.

A possible consideration in your situation is to perform a bulk upsert in the batch mode, do minimum processing on the error results csv file (remove the last column "ERROR") and do a 2nd batch mode run with batch size = 1.

**Comment by ashitsalesforce** [comment] 2022-06-08 06:50
closing the issue as it seems to be resolved based on above comments.

**Closed by ashitsalesforce** 2022-06-08 06:50 UTC
