### ISSUE TITLE
Results length must be the same as the data.  Stopping output writer.

### ISSUE THREAD

**Issue by lance-demo** [forcedotcom/dataloader#803] opened 2023-09-06 01:20 UTC
**Describe the bug**
Facing issue "Results length must be the same as the data.  Stopping output writer." when upserting Account. The upsert stops and only the 5 out 1586 records are saved

**To Reproduce**
1. Open Dataloader
2. Click Upsert
3. For data mapping, we use Account_Migration_ID__c (Text) to match Account and Name for RecordType and FederationIdentifier for Owner
4. Continue and start the import, and see the error

**Expected behavior**
Should all be inserted correctly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5
 - Version V59.0.0

**Additional context**
For security reasons, I cannot share the data schema and the data here. But we do have 54 fields to upsert and not all the fields have values for all records

**Comment by ashitsalesforce** [comment] 2023-09-06 01:48
Hi @lance-demo , thanks for reporting the issue. As initial troubleshooting steps, are you seeing this issue in [v58.0.4](https://github.com/forcedotcom/dataloader/releases/tag/v58.0.4), the release prior to the current one? Also, are you using bulk API for upload? Lastly, have you captured the console output?

**Comment by ashitsalesforce** [comment] 2023-09-18 21:20
closing assuming the issue is resolved.

**Closed by ashitsalesforce** 2023-09-18 21:20 UTC

**Comment by ashitsalesforce** [comment] 2023-09-19 00:52
Closing assuming that the issue is resolved.
