### ISSUE TITLE
Please set minimum window width that show full content of the window.

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/dataloader#1017] opened 2024-03-11 10:09 UTC
**Describe the bug**
When I am using Data Loader 60.0.2 I need to resize the window on each step to see its full content. 

**To Reproduce**
1. Open data loader
2. Click on Update (other paths have the same issue), Button Cancel is cut out:
<img width="336" alt="2024-03-11_10h59_01" src="https://github.com/forcedotcom/dataloader/assets/5740564/80eca3fa-fa90-49d2-bbc9-5aa097b69bc4">

3. Load Updates screen has Browse and Cancell button cut out:
<img width="287" alt="2024-03-11_11h00_17" src="https://github.com/forcedotcom/dataloader/assets/5740564/4aa0a18e-7266-4f7f-901b-7236ec3da29c">

4. Load Updates Step 2b has Lookup fields cut out:
<img width="281" alt="2024-03-11_11h01_19" src="https://github.com/forcedotcom/dataloader/assets/5740564/57a75cfd-6a12-450a-8cc4-ca531dafa4ac">

5. Mapping screen has right column cut and Cancell button
<img width="281" alt="2024-03-11_11h02_06" src="https://github.com/forcedotcom/dataloader/assets/5740564/059ba2b2-90a1-4065-b0e4-c90cb48ac110">

6. Step 4 Finish screen has browse and cancell button cut out.
<img width="281" alt="2024-03-11_11h03_58" src="https://github.com/forcedotcom/dataloader/assets/5740564/796bdf90-5838-4ec5-9ff4-2fd279b3e5fd">

**Expected behavior**
Screen size is big enough to show all components.

**Screenshots**
In error description

**Desktop (please complete the following information):**
- Windows 11 23H2 
- Dataloader 60.0.2 and all previous 

**Additional context**

**Comment by ashitsalesforce** [comment] 2024-03-11 16:46
Hi @PawelWozniak , we are unable to reproduce this issue with Windows 11 and a few screen resolutions such as 1024x768 and 800x600. What screen resolution are you using?

**Comment by PawelWozniak** [comment] 2024-03-15 09:36
@ashitsalesforce I can confirm that behavior changes with scaling value and the worst case is at 150% which is system recommended for that 4k resolution.
100%
![2024-03-15_10h28_15](https://github.com/forcedotcom/dataloader/assets/5740564/0912978c-b19d-4fa0-a947-0d36c52a9fe9)
125%
![2024-03-15_10h30_10](https://github.com/forcedotcom/dataloader/assets/5740564/ec7080e5-4d16-48b7-bd2c-bb750c9ddcaa)
150% (system recommended)
<img width="281" alt="2024-03-15_10h31_40" src="https://github.com/forcedotcom/dataloader/assets/5740564/265a3748-1d10-47b0-baee-af2b111fc01d">
175%
![2024-03-15_10h33_46](https://github.com/forcedotcom/dataloader/assets/5740564/4243c49d-502b-483f-af20-dba6c1fad25e)

**Comment by ashitsalesforce** [comment] 2024-03-15 17:19
Thanks @PawelWozniak . Data Loader code uses Eclipse SWT for UI and does not set fixed width or height for SWT Wizard and its Shell based on our code inspection. So, likely that SWT components are not providing correct dimension information to their parent container for certain screen resolution. Not sure if we can do anything about it. Let us know if you have any suggestions.

**Comment by ashitsalesforce** [comment] 2024-03-18 03:21
Hi @PawelWozniak , we have made the changes to render the upload wizard display more flexible. Let us know if this addresses your issue. Here is a patch containing the fix.
[dataloader_v60.0.2.zip](https://github.com/forcedotcom/dataloader/files/14630511/dataloader_v60.0.2.zip)

MD5 (dataloader_v60.0.2.zip) = e03d35b704719546c225eeb1cb0af21d

**Comment by PawelWozniak** [comment] 2024-03-18 22:08
Now it seems to be too big. 4k, scaling 150%
<img width="1442" alt="2024-03-18_23h06_34" src="https://github.com/forcedotcom/dataloader/assets/5740564/81058b7f-ed21-49ee-b845-c616dd04a81a">
Scaling 100%
![2024-03-18_23h08_10](https://github.com/forcedotcom/dataloader/assets/5740564/c7eb9f71-4616-4146-b9ae-d9b8f74ae69a)

**Comment by ashitsalesforce** [comment] 2024-03-19 19:05
Hi @PawelWozniak , thanks for trying it. Here is a modified [dataloader_v60.0.2.zip](https://github.com/forcedotcom/dataloader/files/14655177/dataloader_v60.0.2.zip). 

MD5 (dataloader_v60.0.2.zip) = f75f8838250072c4c52f9e67fae76501

**Comment by ashitsalesforce** [comment] 2024-03-20 15:50
Hi @PawelWozniak , we have introduced a couple of settings to be able to specify wizard width and height and use them as hints for wizard sizing or enforce them. Here is the screenshot:

<img width="885" alt="Screenshot 2024-03-20 at 8 35 45 AM" src="https://github.com/forcedotcom/dataloader/assets/71143047/fe05471b-534a-43d2-a0a5-4076dcddda9b">


Here is the corresponding patch:
[dataloader_v60.0.2.zip](https://github.com/forcedotcom/dataloader/files/14669083/dataloader_v60.0.2.zip)

MD5 (dataloader_v60.0.2.zip) = 6e1c91aa185dbe9608b7babbd1b76244

**Comment by PawelWozniak** [comment] 2024-03-21 07:54
Apologies for delay in testing. 
Tested MD5 (dataloader_v60.0.2.zip) = f75f8838250072c4c52f9e67fae76501 
No improvements.

Tested MD5 (dataloader_v60.0.2.zip) = 6e1c91aa185dbe9608b7babbd1b76244
With own defined resolution of 1000 x 1200 it looks fine. 
Still header is cut but at least window is big enough for comfortable use.
<img width="570" alt="2024-03-21_08h49_23" src="https://github.com/forcedotcom/dataloader/assets/5740564/511d1dba-7477-4f71-a8a3-f57c5468dc32">

But now Export screen is affected, could you please change list of fields so it resize with window size change 
<img width="481" alt="2024-03-21_08h51_04" src="https://github.com/forcedotcom/dataloader/assets/5740564/1435c7e5-6c7d-448c-b47f-c95da34fdf69">

**Comment by ashitsalesforce** [comment] 2024-03-21 15:48
Hi @PawelWozniak , horizontal expansion of field list area occurs along with horizontal expansion of condition settings (where clause) on the right side. We have tweaked the code to stop horizontal expansion of condition settings and have the field list area fully expand horizontally. Attaching the patch to check if that is more along the lines of what you are looking for.

[dataloader_v60.0.2.zip](https://github.com/forcedotcom/dataloader/files/14702552/dataloader_v60.0.2.zip)

MD5 (dataloader_v60.0.2.zip) = cd9771415e7c06e7975a0b78a7c55299

**Comment by PawelWozniak** [comment] 2024-03-22 08:27
Hi. I have tested that build. Still vertical resize is needed. 
<img width="504" alt="2024-03-22_09h18_47" src="https://github.com/forcedotcom/dataloader/assets/5740564/e1c6509d-838a-4684-aab6-60f82fdc5b93">
I would expect such resize:
<img width="504" alt="2024-03-22_09h18_47" src="https://github.com/forcedotcom/dataloader/assets/5740564/0f0575b9-c52d-4bf4-bddf-dad933664d9b">

Also setup could be improved with vertical resize:
<img width="652" alt="2024-03-22_09h21_25" src="https://github.com/forcedotcom/dataloader/assets/5740564/49c4478f-46fa-4631-8b93-4583f2c493e5">

**Comment by ashitsalesforce** [comment] 2024-03-22 15:25
Thanks @PawelWozniak for indentifying these and pointing out fix suggestions. Here is a patch containing their fix.

[dataloader_v60.0.2.zip](https://github.com/forcedotcom/dataloader/files/14724666/dataloader_v60.0.2.zip)

MD5 (dataloader_v60.0.2.zip) = 16f169fd3dfc7045f6cecd41378586fe

**Comment by PawelWozniak** [comment] 2024-03-25 12:24
Export looks great
<img width="491" alt="2024-03-25_13h14_28" src="https://github.com/forcedotcom/dataloader/assets/5740564/9c7a6c63-8653-45fe-bb0d-47344c0ef35f">
Settings also resize well
<img width="652" alt="2024-03-25_13h15_14" src="https://github.com/forcedotcom/dataloader/assets/5740564/328b4f83-3ca5-46b2-baeb-4fe86e5cad20">

Good job. 🏆That solves most important usability issues.
Two small issues left:
Header is still cut (UI wizard resolution in setup is set to 1000x1200)
<img width="266" alt="2024-03-25_13h18_32" src="https://github.com/forcedotcom/dataloader/assets/5740564/664aeeb3-0ecd-4227-a343-70fec4dc1b83">

Login button is squeezed
<img width="347" alt="2024-03-25_13h20_31" src="https://github.com/forcedotcom/dataloader/assets/5740564/f6426234-a22e-4734-8a4d-68d7b2c46dd4">

Other than that I don't find anythig else.

**Comment by ashitsalesforce** [comment] 2024-03-26 06:56
Hi @PawelWozniak , here is the zip file containing fix for partially rendered login button and details covered by grey bar.

[dataloader_v60.0.2.zip](https://github.com/forcedotcom/dataloader/files/14753849/dataloader_v60.0.2.zip)

MD5 (dataloader_v60.0.2.zip) = ce979eaa9a3999155eb1042114b49be7

**Comment by PawelWozniak** [comment] 2024-03-26 07:34
Hi. Button looks good:
<img width="376" alt="2024-03-26_08h31_27" src="https://github.com/forcedotcom/dataloader/assets/5740564/707e345c-b399-4467-bb24-2a29b7151276">
Header also is fixed:
<img width="242" alt="2024-03-26_08h32_16" src="https://github.com/forcedotcom/dataloader/assets/5740564/46f3c4dc-bb66-47e4-884c-f9ec9190d779">

Thank you for all your works. I don't find any other visual issues.

**Comment by ashitsalesforce** [comment] 2024-03-26 15:07
Closing this as all issues are resolved.

**Closed by ashitsalesforce** 2024-03-26 15:07 UTC
