### ISSUE TITLE
Unable to write logs of dataloader operations in external log file

### ISSUE THREAD

**Issue by Shreyansh1004** [forcedotcom/dataloader#426] opened 2022-01-24 11:17 UTC
I am trying to write the logs of dataloader upsert operations in a file, but the logs are not getting written in the file even though the log-conf.xml file has the console parameter. I am using dataloader-53.0.3-uber-jar
Example - 
        java -cp dataloader-53.0.3-uber.jar com.salesforce.dataloader.process.DataLoaderRunner salesforce.config.dir=%1 run.mode=batch process.name=opportunityUpsertProcess > upsert.log
So the log of this opportunityUpsertProcess should go to the upsert.log file but only 2 lines are getting written in that file other than that no lines are getting written. 
Previously I was using 44.0.0 in which it is getting appended but don't know why it is not happening with the new version

**Comment by ashitsalesforce** [comment] 2022-01-24 19:03
Hi @Shreyansh1004 , it is likely that your log-conf.xml uses log4j 1.x format whereas log4j 2.x has a different format. Can you provide your log-conf.xml so that we can look at it to troubleshoot this further?

**Comment by ashitsalesforce** [comment] 2022-01-27 19:05
closing assuming that the issue is resolved.

**Closed by ashitsalesforce** 2022-01-27 19:05 UTC
