### ISSUE TITLE
Failed unit test

### ISSUE THREAD

**Issue by jgleonard-takeda** [forcedotcom/dataloader#708] opened 2023-06-26 15:42 UTC
**Describe the bug**
[ERROR] Failures:
[ERROR] CsvTest.testCSVReadUTF8BOMBasic:77->testCSVReadBasic:96

**To Reproduce**

Dockerfile:
```Dockerfile
FROM alpine:latest as base
RUN apk update && apk --no-cache add bash openjdk17-jdk git maven zip
WORKDIR /tmp
RUN git clone https://github.com/forcedotcom/dataloader.git && \
    cd dataloader && \
    git checkout v58.0.3 && \
    git submodule init && \
    git submodule update
WORKDIR /tmp/dataloader

# run a mvn build to download dependencies from the central maven repo
RUN  mvn clean compile

# build uber jar
RUN mvn clean package
```

Build:  `docker build . -t dataloader`

**Expected behavior**
A clean build with no errors

**Log**
```
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 51.457 s <<< FAILURE! - in com.salesforce.dataloader.dao.CsvTest
[ERROR] com.salesforce.dataloader.dao.CsvTest.testCSVReadUTF8BOMBasic  Time elapsed: 6.245 s  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.salesforce.dataloader.dao.CsvTest.testCSVReadBasic(CsvTest.java:96)
	at com.salesforce.dataloader.dao.CsvTest.testCSVReadUTF8BOMBasic(CsvTest.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

[INFO] Running com.salesforce.dataloader.EncryptionUtil.EncryptionUtilTest
2023-06-26 15:39:59,629 INFO  [main] EncryptionUtil.EncryptionUtilTest testEncryptionToAKeyFile (EncryptionUtilTest.java:89) -
Encrypted key:fc1fe617ea4e91f719668eb2025393390c3c9f869ded498ee147a437837060cd3810e23ce58688b26bdd2ac44bfa4320
Text to be encrypted:somePassword6c3708b3
Decrypted       text:somePassword6c3708b3
2023-06-26 15:39:59,634 INFO  [main] security.EncryptionAesUtil createUserProfileKeyName (EncryptionAesUtil.java:136) - /root/.dataloader was created
2023-06-26 15:39:59,637 INFO  [main] EncryptionUtil.EncryptionUtilTest testAutoSetKeyFile (EncryptionUtilTest.java:126) -
Encrypted message:b6130dd62a43c38bd6fb020b0bbc24a16272209ff6114bfafd0b5651258be9a562b9c0714e55b8450fc09825dc0be765
Text to be encrypted:somePassword6c3708b3
Decrypted       text:somePassword6c3708b3
2023-06-26 15:39:59,638 INFO  [main] EncryptionUtil.EncryptionUtilTest testEncryption (EncryptionUtilTest.java:58) -
Encryption key:[B@1595d2b2
2023-06-26 15:39:59,638 INFO  [main] EncryptionUtil.EncryptionUtilTest testEncryption (EncryptionUtilTest.java:61) -
Encrypted message:[B@20349058
Text to be encrypted:somePassword6c3708b3
Decrypted       text:somePassword6c3708b3
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.019 s - in com.salesforce.dataloader.EncryptionUtil.EncryptionUtilTest
[INFO] Running com.salesforce.dataloader.action.ExtractTest
2023-06-26 15:39:59,652 ERROR [main] action.AbstractExtractAction getColumnsFromSoql (AbstractExtractAction.java:97) - Error in query: query is empty
2023-06-26 15:39:59,652 ERROR [main] action.AbstractExtractAction getColumnsFromSoql (AbstractExtractAction.java:97) - Error in query: query is empty
2023-06-26 15:39:59,652 ERROR [main] action.AbstractExtractAction getColumnsFromSoql (AbstractExtractAction.java:107) - Error in query: missing [select ]:  from Account
2023-06-26 15:39:59,652 ERROR [main] action.AbstractExtractAction getColumnsFromSoql (AbstractExtractAction.java:126) - Error in query: missing [ from ]: select field1, field2, field3 from
java.lang.StringIndexOutOfBoundsException: begin 7, end -1, length 32
	at java.lang.String.checkBoundsBeginEnd(String.java:4602) ~[?:?]
	at java.lang.String.substring(String.java:2705) ~[?:?]
	at com.salesforce.dataloader.action.AbstractExtractAction.getColumnsFromSoql(AbstractExtractAction.java:114) [dataloader-58.0.3.jar:?]
	at com.salesforce.dataloader.action.ExtractTest.negativeQueryParse(ExtractTest.java:95) [test-classes/:?]
	at com.salesforce.dataloader.action.ExtractTest.testQueryParseNegative(ExtractTest.java:83) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316) [surefire-junit4-3.1.0.jar:3.1.0]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240) [surefire-junit4-3.1.0.jar:3.1.0]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214) [surefire-junit4-3.1.0.jar:3.1.0]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155) [surefire-junit4-3.1.0.jar:3.1.0]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385) [surefire-booter-3.1.0.jar:3.1.0]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162) [surefire-booter-3.1.0.jar:3.1.0]
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507) [surefire-booter-3.1.0.jar:3.1.0]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495) [surefire-booter-3.1.0.jar:3.1.0]
2023-06-26 15:39:59,655 ERROR [main] action.AbstractExtractAction getColumnsFromSoql (AbstractExtractAction.java:107) - Error in query: missing [select ]: account field1, field2, field3 from select
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 s - in com.salesforce.dataloader.action.ExtractTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   CsvTest.testCSVReadUTF8BOMBasic:77->testCSVReadBasic:96
[INFO]
[ERROR] Tests run: 110, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:05 min
[INFO] Finished at: 2023-06-26T15:39:59Z
[INFO] ------------------------------------------------------------------------
[WARNING]
[WARNING] Plugin validation issues were detected in 8 plugin(s)
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.2.0
[WARNING]  * org.apache.maven.plugins:maven-jar-plugin:3.2.2
[WARNING]  * org.apache.maven.plugins:maven-clean-plugin:3.1.0
[WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[WARNING]  * org.apache.maven.plugins:maven-enforcer-plugin:3.0.0
[WARNING]  * org.apache.maven.plugins:maven-antrun-plugin:3.0.0
[WARNING]  * org.apache.maven.plugins:maven-shade-plugin:3.4.1
[WARNING]  * com.mycila:license-maven-plugin:4.2.rc2
[WARNING]
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.0:test (unit-tests) on project dataloader: There are test failures.
[ERROR]
[ERROR] Please refer to /tmp/dataloader/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by jgleonard-takeda** [comment] 2023-06-26 16:46
See attached step by step process to reproduce.

Running in a container on a Mac M2.

[build.log](https://github.com/forcedotcom/dataloader/files/11871641/build.log)

**Comment by ashitsalesforce** [comment] 2023-06-26 16:59
Hi @jgleonard-takeda , it seems that you are trying to build data loader in a linux container on Mac M2 whereas we build it natively. I suggest trying native build on Mac M2 and see if you can reproduce the issue in order to further troubleshoot it.

**Comment by jgleonard-takeda** [comment] 2023-06-26 17:00
It has the same failure within GitHub Actions on a Linux runner.

**Comment by ashitsalesforce** [comment] 2023-06-26 17:06
Hi @jgleonard-takeda , I do not understand your point as I am not familiar with GitHub Actions. Our build and test process runs on Mac and Windows and uses `dlbuilder.sh` as a part of it.

**Comment by jgleonard-takeda** [comment] 2023-06-26 20:19
It's happening using the Alpine docker container, but not on Mac.  Perhaps it's because of the linux image, but it was working up until 58.0.2 and then 58.0.3 broke it.

**Comment by ashitsalesforce** [comment] 2023-06-26 20:53
58.0.2 was released after PR #692. 58.0.3 was released after PR#702. So, the PRs merged from 693 to 702 are suspect. Unfortunately we can't reproduce the issue and therefore can't troubleshoot it.

**Comment by jgleonard-takeda** [comment] 2023-06-27 20:35
> 58.0.2 was released after PR #692. 58.0.3 was released after PR#702. So, the PRs merged from 693 to 702 are suspect. Unfortunately we can't reproduce the issue and therefore can't troubleshoot it.

Have you tried the dockerfile?

**Comment by ashitsalesforce** [comment] 2023-06-27 20:39
No, but I am willing to give it a try if you provide me the steps - you will have to start from the beginning - how to download docker and so on as I haven't worked with Docker before.

**Comment by ashitsalesforce** [comment] 2023-06-28 00:54
Hi @jgleonard-takeda , I have been able to reproduce the issue on a Linux VM running in Mac. So, we can eliminate docker commands from the possible root-cause.

**Closed** 2023-06-28 15:53 UTC

**Comment by jgleonard-takeda** [comment] 2023-06-28 16:52
Thanks! Sorry for the delayed response, got a bit busy over here. Much appreciated
