### ISSUE TITLE
Issue - https://github.com/forcedotcom/dataloader/issues/436

### ISSUE THREAD

**Issue by gvpatel** [forcedotcom/dataloader#506] opened 2022-06-30 12:59 UTC
Hi @ashitsalesforce,

Salesforce support is useless. NO HELP.

https://github.com/forcedotcom/dataloader/issues/436

This issue is BIG show stopper. We're working with support since last 2 years and NO HELP.

can your team help?

Thanks,

**Comment by ashitsalesforce** [comment] 2022-06-30 16:19
Hi @gvpatel , sorry to hear that your issue is not yet resolved. There is only one way to get support from Salesforce. There is no other team at Salesforce that provides support to customers. The help provided in github forum is voluntary and is from users such as yourself and developers, both Salesforce and non-Salesforce developers. As such, you may not get a timely (or any) response for your issue from the forum.  Consequently, if you have urgent need for resolution or sensitive information that you do not want to share in public, Salesforce support is the right choice.

My understanding from issue #436 and from case records is that the results CSV files (success and error csv) for your upsert operation have some records incorrect - a few successfully upserted records show up in error csv and vice-versa. Internal records show that the support team had requested the following:
Assuming that you are performing the batch upsert operation "LNaccountUpsert" in `process-conf.xml` and assuming that OCPGUID__C is the external id field on which upsert is performed, we want you to try reproduce the issue with as small as possible number of fields and records and provide the details of what you did and results. For example, you may try performing an upsert with the 2 fields `NAME` and `OCPGUID__C` and 5 records to see if the issue is reproduced. If the issue is reproduced, provide the csv file on which upsert was performed, expected results, and actual results. If the issue does not occur, add one field at a time and retry till the issue occurs. The full list of fields on which your upsert operation is performed is 
`NAME,ACCOUNT_STATUS__C,ADDR,ADDRESS_LINE_1__C,ADDRESS_LINE_2__C,ADDRESSPGUID__C,ANNUALREVENUE,BILLINGCITY,BILLINGCOUNTRY,BILLINGPOSTALCODE,BILLINGSTATE,BUSINESS_UNIT__C,CATEGORY__C,COUNTY__C,CUST_ID__C,CUSTOMER_CLASS__C,CUSTOMER_SUB_CLASS__C,OC_REPAIR_FLAG__C,F1000_RANK__C,GLOBAL_500_RANK__C,INCORPORATION_DATE__C,INDUSTRY_CLASS__C,INDUSTRY_SUB_CLASS__C,NUMBER_OF_ATTORNEYS__C,NUMBER_OF_EMPLOYEES__C,NUMBER_OF_STUDENTS__C,OCPGUID__C,PHONE,POBPGUID__C,PRACTICE_AREA__C,PRICING_SEGMENT__C,SECONDARY_SUB_CLASS__C,TICKERSYMBOL,WEBSITE,SFDC_ID,FORBES_PVT_RANK__C,PENDING_PHONE__C,DS_LAST_VERIFIED_DATE__C,CREDIT_STATUS__C,CONFIDENCE__C,ALLFIELDS`

**Comment by ashitsalesforce** [comment] 2022-06-30 23:42
Hi @gvpatel , you can also try by surrounding each field value in your csv file with double-quote character.

**Comment by gvpatel** [comment] 2022-07-02 19:35
Thanks @ashitsalesforce,

In last 2 years we've spent enough time with Salesforce support. It seems Support is NOT interested in fixing the issue. 

We've tried all suggestions given by support.

https://github.com/forcedotcom/dataloader/issues/436

https://github.com/forcedotcom/dataloader/issues/230

**Comment by ashitsalesforce** [comment] 2022-07-03 00:54
Hi @gvpatel , thanks for pointing out issue #230. Going through it and looking at Reference W-4273711, I tried to reproduce the issue by taking the following steps:

- Use v54.0.0 of Data Loader
- Check the checkbox "Use Bulk API" in Settings dialog
- Create a CSV file containing the following data
```
CreatedDate,Name
2017-08-05T01:26:58.000Z,CompanyA
2017-01-14T24:13:00.000Z,CompanyB
2017-08-05T01:26:57.000Z,CompanyC
```

If issue #230 is fixed, results would be as follows:
success CSV:
```
"xxxxxxxxxxxxxxxxxxxxxx","2017-08-05T01:26:58.000Z","CompanyA","Item Created"
"xxxxxxxxxxxxxxxxxxxxxx","2017-08-05T01:26:57.000Z","CompanyC","Item Created"
```
error CSV:
```
"CREATEDDATE","NAME","ERROR"
"2017-01-14T24:13:00.000Z","CompanyB","Error converting value to correct data type: Failed to parse date: 2017-01-14T24:13:00.000Z"
```

I verified this with v54.0.0. So, I am unable to reproduce the issue #230 based on the information captured in W-4273711. If you are able to reproduce issue #230, let us know with the details such as input CSV with the same columns as the ones reported in issue #230 and expected results so that we can try to reproduce the issue.

Thanks

**Comment by ashitsalesforce** [comment] 2022-07-06 17:08
Hi @gvpatel ,

My team needs to reproduce the issue on our desktops with the following details to identify the root-cause and fix it:

1. Much smaller dataset, no more than a handful of columns and rows. We currently do not have this.
2. Same code (we know that already through affected versions - v54.0.0 and earlier).
3. Similar config (we can get that easily through config files) and we believe we have this information from prior interactions.

A meeting will unlikely help with obtaining a smaller dataset where the issue is reproducible. Moreover, my colleagues or I cannot join a customer support call unless mediated through Salesforce support. 

My understanding from your colleague's comments in issue #436, the issue was reproducible even with CSV file import. So, the fact that you are using JDBC/Oracle DB does not seem to be contributing to the issue. I will reiterate the ask: give us a CSV with as few columns and rows as possible where the issue is reproducible so that we can reproduce it, identify the root-cause, and provide a workaround or a fix.

**Comment by ashitsalesforce** [comment] 2022-07-19 16:12
Hi @gvpatel ,

I was going over the data and comments from the two previously reported issues (#230 and #436). Here is a comment from #230 : 
"Hi,
This Issue is not fixed and still facing the same issue with 52 and 54 versions as well.
I have attached the Success and Error files where you can see Error Records are present in Success Table and also, Success Sheet with incorrect data like Customer Class/Cusotmer Sub Class are Required fields for every Account, where as some records with blank or #NA values records are showing in Success sheet without any error."

Looking at the success csv provided from #436 , I found that Clustomer Class is likely to be the field `Customer_Class__C` and Customer Sub Class is likely to be the field `Customer_Sub_Class__C` on Lead entity. If so, what is the data type of these fields (e.g. text, picklist)? Also, do that have any constraints (e.g.  required) or attributes (e.g. default value)?

**Comment by ashitsalesforce** [comment] 2022-07-20 03:45
Thanks @gvpatel for these details. Let's start with why Account upsert is not working as expected. What are the possible values for Customer_Class__C and Customer_Sub_Class__C picklists in Account object?

**Comment by ashitsalesforce** [comment] 2022-07-20 03:47
Also, as FYI, Support is aware of our discussion here as I am updating internal investigation record with our discussion.

**Comment by ashitsalesforce** [comment] 2022-07-20 14:58
Hi @gvpatel,

Thanks for clarifying that the upsert operation succeeds but success and error files do not correctly report the input rows that succeeded and the input rows that failed.

To try and reproduce this issue, I have added customer_class_c and customer_sub_class_c fields to Account in my org:
<img width="1356" alt="Screen Shot 2022-07-20 at 7 36 19 AM" src="https://user-images.githubusercontent.com/71143047/180010635-999c8095-308f-4b37-b23a-9d524cb07459.png">

with the following Account validation rules:
<img width="1375" alt="Screen Shot 2022-07-20 at 7 36 48 AM" src="https://user-images.githubusercontent.com/71143047/180010826-b4f5370d-fdf6-4abe-b2f8-8b2d2643685d.png">

and following picklist values for customer_class__c and customer_sub_class__c fields:
<img width="1350" alt="Screen Shot 2022-07-20 at 7 37 25 AM" src="https://user-images.githubusercontent.com/71143047/180010882-6ecd1a95-096a-46f5-bbe6-7e5495974d40.png">

Next, I used the following CSV file for an upsert operation (bulk enabled with batch size of 2) using Oracle_id field as the external id field:
[AccountWrongDateFormat.csv](https://github.com/forcedotcom/dataloader/files/9150854/AccountWrongDateFormat.csv)

Here is the success file:
[success072022072806125.csv](https://github.com/forcedotcom/dataloader/files/9150867/success072022072806125.csv)

Here is the error file:
[error072022072806125.csv](https://github.com/forcedotcom/dataloader/files/9150870/error072022072806125.csv)

The surprise for me was the message in the "ERROR" column. It is "INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST:Customer Class: bad value for restricted picklist field: #NA" whereas I was expecting "FIELD_CUSTOM_VALIDATION_EXCEPTION:Customer Class and Customer Sub Class are required fields" due to the triggering of the custom validation rule, which would be similar to the values in "ERROR" column of the error csv files you have ("FIELD_CUSTOM_VALIDATION_EXCEPTION:Customer Class, Customer Sub-Class and Secondary Sub-Class are required fields, please select a value in each field.").

On the other hand, it makes sense that an invalid picklist value for customer_class__c field ("#NA") is caught by prebuilt filed validation rule and makes me wonder why that is not the case for your upserts.

While I did not see in your screenshot, I want to confirm that you do not have "#NA" as a picklist value for customer_class__c or customer_sub_class__c or customer_secondary_class__c fields. Also, I would like you to try with a smaller CSV such as the one I used to see whether upserts produce expected results.

**Comment by ashitsalesforce** [comment] 2022-07-21 16:27
Hi @gvpatel , thanks for confirming that "#NA" is not a picklist value.

I went over previously provided success and error csv files by hanuma1111 as part of issue #436 and have following questions/comments:
- One possibility is that data from a row of the input csv triggers incorrect placement of that row and subsequent rows in success and error files. I have success and error csvs but do not have the input csv file to validate this hypothesis. Can you look into to see if misplacement of rows starts at or after a specific input row? For example, I see an account with ID "00153000008bJXNAA2" (OCPGUID = urn:ecm:4255JWNST) as the first row in the success csv. However, its cust_class__c column has value "#NA" indicating it must have failed to upsert. If so, what was the row before it? If not (i.e. it was the first row in the input csv), I suggest retry upsert operation with only that row in the input csv and see if the issue reproduces. If there was a row before it, I suggest trying with 2 rows: the previous row and the row where incorrect output occurs to see if the issue reproduces.
- A number of columns besides customer_class__c, customer_sub_class__c, and secondary_class__c have value "#NA" in them (category__c, cust_id__c, global_rank__c, and so on). Are any of them picklists? Are any of them mandatory? have any custom validation rules?

**Comment by ashitsalesforce** [comment] 2022-07-22 02:12
Hi @gvpatel , thanks for clarifying where "#NA" values come from. 

As part of troubleshooting #436, I had requested trying with CSV based data upload for the operation instead of DB based data upload as it is easier to transfer CSV files to Support so that they can try to replicate the issue. My understanding is that hanuma1111 was able to reproduce the issue with a CSV based data upload. 

What did you use before migrating the system to Salesforce? Why do you think it is likely a bug in Spring framework code?

**Comment by ashitsalesforce** [comment] 2022-07-23 03:42
Hi @gvpatel, thanks for the context regarding migration. 

Here is how data loader uploads data and stores results:
1. data loader reads one row from Oracle using JDBC driver.
2. data loader processes the data and may reject a row during this step.
3. data loader sends a single batch's data to server when a batch's worth of data is read from Oracle.
4. data loader repeats steps 1 through 3 till there is no more data to read in Oracle.
5. data loader makes sure that all batches in the job are completed and then takes the next steps.
6. data loader reads a batch's results from the server and matches each row in the result with the row read from the database. Next, it stores the results to success or error file after blending the row read from Oracle with the interpretation of results from the server.
7. data loader repeats step 6 for all batches in the job.

I have made a code change to capture the data uploaded to the server per batch and the raw batch results received from the server to be able to troubleshoot the issue further. To do so, download  
[dataloader v55.0.4 for Windows](https://github.com/forcedotcom/dataloader/files/9173016/dataloader_win.zip) (md5: 5588cc2a1da85a0976fb2eaad48c75e3) and set the property `process.bulk.saveServerLoadAndRawResultsInCSV` to `true` in `config.properties`. You will see files with prefix `uploadedToServer_Batch` and `rawResultsFromServer_Batch` after running data loader in the same folder where success and error csv files are created. You can then look at each batch's `uploadedToServer_Batch` file and see if the corresponding row in that batch's `rawResultsFromServer_Batch` file show correct results.

Example:
I tried to upsert 5 records using Bulk upsert operation where batch size was 2. All 5 failed to upsert. Following files were created:
```
error072222061650953.csv
rawResultsFromServer_Batch1_072222061650953.csv
rawResultsFromServer_Batch2_072222061650953.csv
rawResultsFromServer_Batch3_072222061650953.csv
success072222061650953.csv
uploadedToServer_Batch1_072222061650953.csv
uploadedToServer_Batch2_072222061650953.csv
uploadedToServer_Batch3_072222061650953.csv
```
Here is the content of `uploadedToServer_Batch1_072222061650953.csv`:
```
Name,Oracle_Id__c,Description,RichText__c
"acct_with_extid1","o1","first","&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;leading&nbsp;space&nbsp;and&nbsp;ending&nbsp;tab&nbsp;"
"acct_with_extid2","o2","second","&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;leading&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;space&nbsp;and&nbsp;ending&nbsp;tab&nbsp;"
```
Here is the content of `rawResultsFromServer_Batch1_072222061650953.csv`:
```
Id, Success, Created, Error
null, false, true, FIELD_CUSTOM_VALIDATION_EXCEPTION:Customer Class and Customer Sub Class are required fields:--
null, false, true, FIELD_CUSTOM_VALIDATION_EXCEPTION:Customer Class and Customer Sub Class are required fields:--
```

Looking at these 2 files, I can deduce that both rows in batch 1 failed to upsert with the error `FIELD_CUSTOM_VALIDATION_EXCEPTION:Customer Class and Customer Sub Class are required fields:--`

**Comment by ashitsalesforce** [comment] 2022-07-25 15:26
Hi @gvpatel , 

I do not know if just using the new jar file will suffice. Likely you will have to modify dataloader.bat to specify the new version if you choose to do so.

Regarding providing the files for analysis, make sure to remove any business-sensitive information before providing them. 

Thanks.

**Comment by ashitsalesforce** [comment] 2022-07-26 02:59
Hi @gvpatel ,

I am including a python3 script that iterates over all csvs in the results folder to compare the content of uploaded batch data csv with raw results csv for incorrectness (success indicated in results when one of the required field values for that row was "#N/A" and vice-versa). If you save it in a file named `getIncorrectSuccessFail.py`, it can be run with the command `python3 getIncorrectSuccessFail.py <folder containing results>` to analyze the results.

```
import sys
import csv
import os
from os.path import exists

def getCSVList(parentDir, namePrefix):
    filelist = []
    for file in os.listdir(parentDir):
        if file.startswith(namePrefix):
            filelist.append(parentDir + "/" + file)
    filelist.sort()
    return filelist

def getUploadedBatchCSVList(parentDir):
    return getCSVList(parentDir, "uploadedToServer_Batch")

def getRawBatchResultsCSVList(parentDir):
    return getCSVList(parentDir, "rawResultsFromServer_Batch")

def checkCorrectness(uploadedBatchCSV, rawBatchResultsCSV):
    print("\nChecking correctness of " + uploadedBatchCSV + " and " + rawBatchResultsCSV)
    with open(uploadedBatchCSV, 'rt') as file_name:
        csv_input = csv.reader(file_name, delimiter=',')
        uploadedBatchHeader = next(csv_input)
        uploadedBatchData = list(csv_input)
    
    with open(rawBatchResultsCSV, 'rt') as file_name:
        csv_input = csv.reader(file_name, delimiter=',')
        rawBatchResultsHeader = next(csv_input)
        rawBatchResultsData = list(csv_input)
    
    if (len(uploadedBatchData) != len(rawBatchResultsData)) :
        print("uploaded batch has " + str(len(uploadedBatchData))
              + " rows, whereas results csv has " + str(len(rawBatchResultsData)) + " rows")
        sys.exit(-1)
    
    i = 0
    customerClassCol = 0
    customerSubClassCol = 0
    secondarySubClassCol = 0
    for col in uploadedBatchHeader:
        if col.casefold().strip() == "CUSTOMER_CLASS__C".casefold():
            customerClassCol = i
        if col.casefold().strip() == "CUSTOMER_SUB_CLASS__C".casefold():
            customerSubClassCol = i
        if col.casefold().strip() == "SECONDARY_SUB_CLASS__C".casefold():
            secondarySubClassCol = i
        i += 1
    
    if customerClassCol == 0:
        print("did not find CUSTOMER_CLASS__C column in uploaded batch")
        sys.exit(-1)
    if customerSubClassCol == 0:
        print("did not find CUSTOMER_SUB_CLASS__C column in uploaded batch")
        sys.exit(-1)
    if secondarySubClassCol == 0:
        print("did not find SECONDARY_SUB_CLASS__C column in uploaded batch")
        sys.exit(-1)
        
    resultsSuccessCol = 0
    resultsErrorCol = 0
    i = 0
    for col in rawBatchResultsHeader:
        if col.casefold().strip() == "Success".casefold():
            resultsSuccessCol = i
        if col.casefold().strip() == "Error".casefold():
            resultsErrorCol = i
        i += 1
    
    if resultsSuccessCol == 0:
        print("did not find Success column in raw batch results")
        sys.exit(-1)
    
    if resultsErrorCol == 0:
        print("did not find Error column in raw batch results")
        sys.exit(-1)
    
    i = 0
    for row in uploadedBatchData:
        if (rawBatchResultsData[i][resultsSuccessCol].casefold().strip() == "true".casefold()
            and (row[customerClassCol].casefold().strip() == "#N/A".casefold()
                 or row[customerSubClassCol].casefold().strip() == "#N/A".casefold()
                 or row[secondarySubClassCol].casefold().strip() == "#N/A".casefold())):
            print("Results mismatch for row " + str(i + 2)
                  + ": Results show operation successful whereas uploaded row contains #N/A for a required field")
            print("uploaded row: ", row)
            print("raw results: ", rawBatchResultsData[i])
        if (rawBatchResultsData[i][resultsSuccessCol].casefold().strip() == "false".casefold()
            and row[customerClassCol].casefold().strip() != "#N/A".casefold()
            and row[customerSubClassCol].casefold().strip() != "#N/A".casefold()
            and row[secondarySubClassCol].casefold().strip() != "#N/A".casefold()):
            print("Results mismatch for row " + str(i + 2)
                  + ": Results show operation failed whereas uploaded row contains all required fields")
            print("  uploaded row: ", row)
            print("  raw results: ", rawBatchResultsData[i])        
        i += 1
    return

if len(sys.argv) != 2 :
    print("Usage: getIncorrectSuccessFail <directory containing results>")
    sys.exit(-1)

uploadedBatchCSVList = getUploadedBatchCSVList(sys.argv[1])
rawBatchResultsCSVList = getRawBatchResultsCSVList(sys.argv[1])

i = 0
for uploadedBatchCSV in uploadedBatchCSVList:
    rawBatchResultsCSV = rawBatchResultsCSVList[i]
    checkCorrectness(uploadedBatchCSV, rawBatchResultsCSV)
    i += 1
```

**Comment by ashitsalesforce** [comment] 2022-07-27 14:57
Hi @gvpatel , v55.0.4 defaults to browser based OAuth login, which displays the screen you see above in your browser. Click on Connect button to go to login screen in your browser and enter your username/password to complete authentication step to perform the operation in Data Loader.

**Comment by ashitsalesforce** [comment] 2022-07-27 16:09
Hi @gvpatel , to troubleshoot why v55.0.4 is not able to find username or password in process-conf.xml or perhaps some other issue that's preventing it from reading username and password in process-conf.xml, set `sfdc.oauth.loginfrombrowser=false` in config.properties and set `<Root level="debug">` in log-conf.xml to get more extensive logging output to help troubleshoot.

**Comment by ashitsalesforce** [comment] 2022-07-27 17:03
Thanks for confirming that the workaround addressed the issue. Will fix it an upcoming release.

**Comment by ashitsalesforce** [comment] 2022-08-09 00:20
Hi @gvpatel ,

Thanks for providing these files. Can you also provide database-conf.xml and config.properties (do scrub them of any sensitive information such as username and password). 

The code reloads the batch rows from your DB to map results returning from Salesforce to specific rows. It is possible that the second execution of the local DB query returns results in a different order (or different results) than the first time when the local DB query was executed for the first time to load the batch data. To avoid this possibility, we have created a patch that stores the entire job's data in-memory, thereby skipping second local DB query execution. However, it increases the java heap space utilization and may result in OutOfMemory exception for very large jobs. So, we recommend using this feature only for troubleshooting purposes.

To use this feature, download the data loader zip containing this change and set the property `process.bulk.cacheDataFromDao=true` before running your upsert operation. Setting `process.bulk.cacheDataFromDao=false` or deleting the property from config.properties reverts the code to the old behavior (execute the local DB query twice).

Thanks.

[dataloader_win.zip](https://github.com/forcedotcom/dataloader/files/9285461/dataloader_win.zip) (MD5: 90ca53dc34dbae95764a7caaeb112678)

**Comment by ashitsalesforce** [comment] 2022-08-09 16:38
Thanks @gvpatel ,

Looking at the SQL query in database-conf.xml,
```
             SELECT /*+ PARALLEL(auto) */  DISTINCT
					NAME,
					ACCOUNT_STATUS__C,
					ADDR,
					ADDRESS_LINE_1__C,
					ADDRESS_LINE_2__C,
					ADDRESSPGUID__C,
					ANNUALREVENUE,
					BILLINGCITY,
					BILLINGCOUNTRY,
					BILLINGPOSTALCODE,
					BILLINGSTATE,
					BUSINESS_UNIT__C,
					CATEGORY__C,
					COUNTRY_PGUID,
					COUNTY__C,
					CURRENCY,
					CUST_ID__C,
					CUSTOMER_CLASS__C,
					CUSTOMER_SUB_CLASS__C,
					F1000_RANK__C,
					GEOG_FLAG,
					GLOBAL_500_RANK__C,
					INCORPORATION_DATE__C,
					INDUSTRY_CLASS__C,
					INDUSTRY_SUB_CLASS__C,
					IP_LOCKOUT_SDESC,
					NUMBER_OF_ATTORNEYS__C,
					NUMBER_OF_EMPLOYEES__C,
					NUMBER_OF_STUDENTS__C,
					OCPGUID__C,
					OC_REPAIR_FLAG__C,
					PHONE,
					POBPGUID__C,
					PRACTICE_AREA__C,
					PRICING_SEGMENT__C,
					RAW_STATE,
					SECONDARY_SUB_CLASS__C,
					TAX_GEOCODE,
					TICKERSYMBOL,
					TOP_PARENT_OCPGUID__C,
					WEBSITE,
					SFDC_ID,
					FORBES_PVT_RANK__C,
					PENDING_PHONE__C,
					DS_LAST_VERIFIED_DATE__C,
					OC_CREDIT_STATUS as Credit_Status__c,
					oc_confidence as Confidence__c,
					'NAME:' || NAME || ' - ACCOUNT_STATUS__C:' || ACCOUNT_STATUS__C || ' - ADDR:' || ADDR || ' - ADDRESS_LINE_1__C:' || ADDRESS_LINE_1__C || ' - ADDRESS_LINE_2__C:' || ADDRESS_LINE_2__C || ' - ADDRESSPGUID__C:' || ADDRESSPGUID__C || ' - ANNUALREVENUE:' || ANNUALREVENUE || ' - BILLINGCITY:' || BILLINGCITY || ' - BILLINGCOUNTRY:' || BILLINGCOUNTRY || ' - BILLINGPOSTALCODE:' || BILLINGPOSTALCODE || ' - BILLINGSTATE:' || BILLINGSTATE || ' - BUSINESS_UNIT__C:' || BUSINESS_UNIT__C || ' - CATEGORY__C:' || CATEGORY__C || ' - COUNTY__C:' || COUNTY__C || ' - CUST_ID__C:' || CUST_ID__C || ' - CUSTOMER_CLASS__C:' || CUSTOMER_CLASS__C || ' - CUSTOMER_SUB_CLASS__C:' || CUSTOMER_SUB_CLASS__C || ' - F1000_RANK__C:' || F1000_RANK__C || ' - GLOBAL_500_RANK__C:' || GLOBAL_500_RANK__C || ' - INCORPORATION_DATE__C:' || INCORPORATION_DATE__C || ' - INDUSTRY_CLASS__C:' || INDUSTRY_CLASS__C || ' - INDUSTRY_SUB_CLASS__C:' || INDUSTRY_SUB_CLASS__C || ' - NUMBER_OF_ATTORNEYS__C:' || NUMBER_OF_ATTORNEYS__C || ' - NUMBER_OF_EMPLOYEES__C:' || NUMBER_OF_EMPLOYEES__C || ' - NUMBER_OF_STUDENTS__C:' || NUMBER_OF_STUDENTS__C || ' - OC_REPAIR_FLAG__C:' || OC_REPAIR_FLAG__C || ' - OCPGUID__C:' || OCPGUID__C || ' - PHONE:' || PHONE || ' - POBPGUID__C:' || POBPGUID__C || ' - PRACTICE_AREA__C:' || PRACTICE_AREA__C || ' - PRICING_SEGMENT__C:' || PRICING_SEGMENT__C || ' - SECONDARY_SUB_CLASS__C:' || SECONDARY_SUB_CLASS__C || ' - TICKERSYMBOL:' || TICKERSYMBOL || ' - WEBSITE:' || WEBSITE || ' - SFDC_ID:' || SFDC_ID || ' - FORBES_PVT_RANK__C:' || FORBES_PVT_RANK__C || ' - PENDING_PHONE__C:' || PENDING_PHONE__C || ' - DS_LAST_VERIFIED_DATE__C:' || DS_LAST_VERIFIED_DATE__C || ' -  Credit_Status__c:' || OC_CREDIT_STATUS || ' -  Confidence__c:' || oc_confidence as ALLFIELDS
			FROM ECMPUBETL.V_SFDC_ORG_CUSTOMER 
				WHERE BUSINESS_UNIT__C in ('USA','BIS','BLSS')
				AND SFDC_ID is null
				AND CATEGORY__C != 'Trial'	
				AND (oc_confidence != 'Low' OR oc_confidence is null)				
				AND LAST_UPDATE_DATE > @process.lastRunDate@
```

It does not have `ORDER BY`. Try replacing the query with the following SQL and re-run your job:
```
             SELECT /*+ PARALLEL(auto) */  DISTINCT
					NAME,
					ACCOUNT_STATUS__C,
					ADDR,
					ADDRESS_LINE_1__C,
					ADDRESS_LINE_2__C,
					ADDRESSPGUID__C,
					ANNUALREVENUE,
					BILLINGCITY,
					BILLINGCOUNTRY,
					BILLINGPOSTALCODE,
					BILLINGSTATE,
					BUSINESS_UNIT__C,
					CATEGORY__C,
					COUNTRY_PGUID,
					COUNTY__C,
					CURRENCY,
					CUST_ID__C,
					CUSTOMER_CLASS__C,
					CUSTOMER_SUB_CLASS__C,
					F1000_RANK__C,
					GEOG_FLAG,
					GLOBAL_500_RANK__C,
					INCORPORATION_DATE__C,
					INDUSTRY_CLASS__C,
					INDUSTRY_SUB_CLASS__C,
					IP_LOCKOUT_SDESC,
					NUMBER_OF_ATTORNEYS__C,
					NUMBER_OF_EMPLOYEES__C,
					NUMBER_OF_STUDENTS__C,
					OCPGUID__C,
					OC_REPAIR_FLAG__C,
					PHONE,
					POBPGUID__C,
					PRACTICE_AREA__C,
					PRICING_SEGMENT__C,
					RAW_STATE,
					SECONDARY_SUB_CLASS__C,
					TAX_GEOCODE,
					TICKERSYMBOL,
					TOP_PARENT_OCPGUID__C,
					WEBSITE,
					SFDC_ID,
					FORBES_PVT_RANK__C,
					PENDING_PHONE__C,
					DS_LAST_VERIFIED_DATE__C,
					OC_CREDIT_STATUS as Credit_Status__c,
					oc_confidence as Confidence__c,
					'NAME:' || NAME || ' - ACCOUNT_STATUS__C:' || ACCOUNT_STATUS__C || ' - ADDR:' || ADDR || ' - ADDRESS_LINE_1__C:' || ADDRESS_LINE_1__C || ' - ADDRESS_LINE_2__C:' || ADDRESS_LINE_2__C || ' - ADDRESSPGUID__C:' || ADDRESSPGUID__C || ' - ANNUALREVENUE:' || ANNUALREVENUE || ' - BILLINGCITY:' || BILLINGCITY || ' - BILLINGCOUNTRY:' || BILLINGCOUNTRY || ' - BILLINGPOSTALCODE:' || BILLINGPOSTALCODE || ' - BILLINGSTATE:' || BILLINGSTATE || ' - BUSINESS_UNIT__C:' || BUSINESS_UNIT__C || ' - CATEGORY__C:' || CATEGORY__C || ' - COUNTY__C:' || COUNTY__C || ' - CUST_ID__C:' || CUST_ID__C || ' - CUSTOMER_CLASS__C:' || CUSTOMER_CLASS__C || ' - CUSTOMER_SUB_CLASS__C:' || CUSTOMER_SUB_CLASS__C || ' - F1000_RANK__C:' || F1000_RANK__C || ' - GLOBAL_500_RANK__C:' || GLOBAL_500_RANK__C || ' - INCORPORATION_DATE__C:' || INCORPORATION_DATE__C || ' - INDUSTRY_CLASS__C:' || INDUSTRY_CLASS__C || ' - INDUSTRY_SUB_CLASS__C:' || INDUSTRY_SUB_CLASS__C || ' - NUMBER_OF_ATTORNEYS__C:' || NUMBER_OF_ATTORNEYS__C || ' - NUMBER_OF_EMPLOYEES__C:' || NUMBER_OF_EMPLOYEES__C || ' - NUMBER_OF_STUDENTS__C:' || NUMBER_OF_STUDENTS__C || ' - OC_REPAIR_FLAG__C:' || OC_REPAIR_FLAG__C || ' - OCPGUID__C:' || OCPGUID__C || ' - PHONE:' || PHONE || ' - POBPGUID__C:' || POBPGUID__C || ' - PRACTICE_AREA__C:' || PRACTICE_AREA__C || ' - PRICING_SEGMENT__C:' || PRICING_SEGMENT__C || ' - SECONDARY_SUB_CLASS__C:' || SECONDARY_SUB_CLASS__C || ' - TICKERSYMBOL:' || TICKERSYMBOL || ' - WEBSITE:' || WEBSITE || ' - SFDC_ID:' || SFDC_ID || ' - FORBES_PVT_RANK__C:' || FORBES_PVT_RANK__C || ' - PENDING_PHONE__C:' || PENDING_PHONE__C || ' - DS_LAST_VERIFIED_DATE__C:' || DS_LAST_VERIFIED_DATE__C || ' -  Credit_Status__c:' || OC_CREDIT_STATUS || ' -  Confidence__c:' || oc_confidence as ALLFIELDS
			FROM ECMPUBETL.V_SFDC_ORG_CUSTOMER 
				WHERE BUSINESS_UNIT__C in ('USA','BIS','BLSS')
				AND SFDC_ID is null
				AND CATEGORY__C != 'Trial'	
				AND (oc_confidence != 'Low' OR oc_confidence is null)				
				AND LAST_UPDATE_DATE > @process.lastRunDate@
                        ORDER BY OCPGUID__C
```

**Comment by ashitsalesforce** [comment] 2022-08-10 02:28
Hi @gvpatel , 

Given that the data is dynamic, you are correct that sorting may not fix the issue as the result set may change by the time job is completed.

JVM can use up to physical memory of the desktop and more (by swapping) depending on the operating system. The error and success files you have provided contain 300 KiloByte of data in ~200 rows (192 rows to be precise). Extrapolating it to 5k rows would mean 7.5 GB of data (data for 25x of 200 rows => 25 x 300 KB = 7.5 MB)  to be retained in memory, which is unlikely to cause an OutOfMemory error if you try `process.bulk.cacheDataFromDao=true`.

**Comment by ashitsalesforce** [comment] 2022-08-10 16:38
Hi @gvpatel , with 1.5KB per row on average, the additional heap space used by data loader with process.bulk.cacheDataFromDao=true will be 1.5GB for a load of 1 million records. If your server has 23 GB RAM and no other apps using significant parts of it, it is unlikely to cause an issue due to lack of memory.

**Comment by ashitsalesforce** [comment] 2022-08-24 03:34
Hi @gvpatel , it has been 2 weeks since the patch was provided. Closing this issue assuming that it has fixed it. Let us know if that's not the case.

**Closed by ashitsalesforce** 2022-08-24 03:34 UTC

**Comment by ashitsalesforce** [comment] 2022-08-24 19:14
@gvpatel , thanks for your patience and help provide data/config necessary to troubleshoot the root-cause.
