### ISSUE TITLE
Data Loader 61.1.0 Ignoring 'Allow field truncation'

### ISSUE THREAD

**Issue by GweiloHKG** [forcedotcom/dataloader#1191] opened 2024-07-02 04:44 UTC
A Contact custom field, HKCC_COMPANY_NAME_C, is defined with maximum length 50.

Data Loader v61.1.0 running on Windows 11, has the option 'Allow field truncation' enabled (tick present).

When performing an Update of Contact, 23 (out of 5,129) records have more than 50 characters defined in HKCC_COMPANY_NAME_C. Prior to Data Loader v61.1.0, these records would update successfully. The custom field's contents would be truncated at 50 characters. No errors would be reported.

With v61.1.0, the records are reported as errors and no update is performed for those records.

[error070224114949623.csv](https://github.com/user-attachments/files/16061760/error070224114949623.csv)
[20240702 Field Too Long.zip](https://github.com/user-attachments/files/16061764/20240702.Field.Too.Long.zip)
![Screen Capture](https://github.com/forcedotcom/dataloader/assets/64362405/3133f071-4e5d-4255-af16-4dd47b94b68a)

**Comment by ashitsalesforce** [comment] 2024-07-02 17:55
Hi @GweiloHKG , I am unable to reproduce the issue on Windows 11 using your `config.properties` and data loader v61.1.0. I used the following CSV file:
```
Account:Account-oracle_id__c,HKCC_COMPANY_NAME,LastName
uo1,"The Hongkong and Shanghai Banking Corporation Limited",Banker
```

I was able to successfully insert a single Contact record using the above CSV with its HKCC_COMPANY_NAME__C field value truncated to `The Hongkong and Shanghai Banking Corporation Limi`.  Can you try the operation with the above value?

**Comment by ankitcommits** [comment] 2024-07-12 09:02
@GweiloHKG Did you find what was the cause?

**Comment by ashitsalesforce** [comment] 2024-07-15 15:58
closing assuming that the issue is resolved.

**Closed by ashitsalesforce** 2024-07-15 15:58 UTC
