### ISSUE TITLE
error while upgrading to 54 version of dataloder on unix server 

### ISSUE THREAD

**Issue by chimpanzee818** [forcedotcom/dataloader#691] opened 2023-06-01 19:19 UTC
hi @ashitsalesforce 

while upgrading the dataloder we have job which perform upsert operation taking csv from folder and map with help of sdl it was working fine but after upgrade we are facing issue 

1 st error
[loadData] mapping.LoadMapper mapData (LoadMapper.java:84) - Mapping for field x,y,z,s,t,end will be ignored since destination column is empty

at last its having error 

 Error message: y not specified
2023-06-01 14:07:44,282 INFO  [loadData] progress.NihilistProgressAdapter setSubTask (NihilistProgressAdapter.java:78) - Processed 73 of 73 total records. Rate: 0 records per hour. Estimated time to complete: 153,722,867,280,912 minutes and 55 seconds.  There are 0 successes and 73 errors.

please take look and thank in advance

**Comment by ashitsalesforce** [comment] 2023-06-01 23:57
Hi @chimpanzee818 , 

Please provide the following:
- Data Loader version where the job succeeded
- Data Loader version after upgrade
- mapping file
- First line of CSV file containing field headers

Thanks

**Comment by ashitsalesforce** [comment] 2023-06-23 01:20
closing assuming that the issue is resolved.

**Closed by ashitsalesforce** 2023-06-23 01:20 UTC
