### ISSUE TITLE
Data Loader Spring Framework CLI results, Success sheet having Error records and Error sheet having Success records. Mis-leading the Reports generated on Transaction History.

### ISSUE THREAD

**Issue by hanuma1111** [forcedotcom/dataloader#436] opened 2022-03-03 16:45 UTC
We are using Data Loader CLI V54.0.0, when we Import the data from external system using Spring Framework, output results are mis -leading. Success file having Error records and Error File having Success records. And also, Error File with Incorrect error message. When we try to run the reports on Transaction History table to work on Error Records, which is giving false information. So, its hard to troubleshoot and find the what are the actual error records (Failed Records). We have raised this issue when we were using v49.0.0 and support team said the issue is fixed in v52.0. but we tried with v52.0 and issue is still exists. I have attached the sample Success and Error files, please go through them and will understand the issue. Please resolve this ASAP as Business escalating as there are many Error records showing in Reports, but they are not actual Error records in reality.
below is the github case reference url: 
https://github.com/forcedotcom/dataloader/issues/230

**Comment by ashitsalesforce** [comment] 2022-03-08 06:57
Hi @hanuma1111 , provide the following:
- Your process-conf.xml file after removing any sensitive or personal information.
- Operation you are performing. 
- Specifics of the CLI invocation.
- Sample input CSV. Make sure to remove any sensitive or personal information.
- Success and error files for the sample input CSV. Make sure to remove any sensitive or personal information.

**Comment by hanuma1111** [comment] 2022-03-10 14:47
[LNaccountUpsertError20220301-171824.csv](https://github.com/forcedotcom/dataloader/files/8224295/LNaccountUpsertError20220301-171824.csv)
[LNaccountUpsertSuccess20220301-171824.csv](https://github.com/forcedotcom/dataloader/files/8224296/LNaccountUpsertSuccess20220301-171824.csv)

**Comment by hanuma1111** [comment] 2022-03-10 14:48
I tried uploading process.conf file but its not accepting the file format.. shall i copy the text inside the file?

**Comment by ashitsalesforce** [comment] 2022-03-12 19:07
Hi @hanuma1111 , you can change it to process-conf.txt and try uploading. Alternately, you can copy the text - make sure to not include any personal or business-sensitive information such as login, password, URL.

**Comment by hanuma1111** [comment] 2022-03-14 14:10
[process.txt](https://github.com/forcedotcom/dataloader/files/8245521/process.txt)
[process-conf-templ.txt](https://github.com/forcedotcom/dataloader/files/8245522/process-conf-templ.txt)

Attached the files in txt format. Please go through them and let me know if you find something.

**Comment by hanuma1111** [comment] 2022-03-14 23:02
Using power shell , we navigate to the folder where we are placing the ps1 file and then calling that file as ./accountUpsert.ps1, attached the file for reference. changed the extension to txt as we can't attach ps1 file.
attached the process-conf executed output file.
Attached the status files also.
Please go through them and let me know if you need anything else.

[accountUpsert.txt](https://github.com/forcedotcom/dataloader/files/8248969/accountUpsert.txt)
[process-conf.txt](https://github.com/forcedotcom/dataloader/files/8248970/process-conf.txt)

[accountErrorSoapTrace.log](https://github.com/forcedotcom/dataloader/files/8248966/accountErrorSoapTrace.log)
[accountMasterSoapTrace.log](https://github.com/forcedotcom/dataloader/files/8248968/accountMasterSoapTrace.log)

**Comment by ashitsalesforce** [comment] 2022-03-15 06:02
Hi @hanuma1111 , the error message for most of the failed rows is 
`FIELD_CUSTOM_VALIDATION_EXCEPTION:Customer Class, Customer Sub-Class and Secondary Sub-Class are required fields, please select a value in each field.`. However,  these columns are not empty in the error csv. So, further troubleshooting will likely require working with Support team.

You may want to verify config.properties file for CSV delimiter settings. These should be as follows:
```
loader.csvComma=true
loader.csvTab=false
loader.csvOther=false
loader.csvOtherValue=-
```

If they are not specified as shown above, change them, and see if that fixes the issue before opening a case with Support.

**Comment by hanuma1111** [comment] 2022-03-16 02:39
Hi,
except of loader.csvTab rest of all same and i changed that to false from True and still the same issue.
I have raised case with support and lets see what they respond.

Thank you very much for your help.

Thanks,
Hanuma.

**Comment by hanuma1111** [comment] 2022-03-21 17:25
Hi,
I have tried with the given inputs and modified the process.con file to read form csv file and ran the job. i see some improvement but not completely, below are my findings

Sceanrio1: I ran the job without the mentioned changes and got few success and errors as normal with incorrect details.
Sceanrio2: I have made the changes to read the data from csv file, I took the success records from the past job and placed in a folder to read them again and they are all success.
Scenario2: I have copied the error file and ran the job, it is processed few records and few are error.
Scenario3: I took the error records from scenario2 and executed the job, again few success and few error.
Sceanrio4: I tried again with errors, and this time no success and same records error. so this time it processed correctly.

It seems like it keep creating success records from error records file. So, keep testing it and let you know if i find anything.
I just want to share the update.

Thanks,
Hanuma.

**Comment by ashitsalesforce** [comment] 2022-03-22 04:04
Hi @hanuma1111 , thanks for trying with multiple iterations. I suggest picking a few (about 5) success records from Scenario 1 and a few error records from scenario 4 (about 5) and see what happens. I would expect 5 successes (from Scenario 1 success records) and 5 errors (from Scenario 4 error records). These will be good to provide to Support for further troubleshooting and narrowing the root-cause.

**Comment by ashitsalesforce** [comment] 2022-03-22 04:48
Hi @hanuma1111 , additionally, if you can select as few as possible (2 ideal, but a handful will do) records from Scenario 1 that would result in some of them successfully upserted and others in errors, that would be helpful in troubleshooting. 

The fact that some of the errors in scenario 1 resulted in success in scenario 2, and some errors in scenario 2 resulted in success in scenario 3 makes us think that the issue is likely with delimiters or escaping/encoding some non-ascii characters.

**Comment by ashitsalesforce** [comment] 2022-03-28 19:14
closing this issue as resolution will be driven through official Support channel.

**Closed by ashitsalesforce** 2022-03-28 19:14 UTC
