### ISSUE TITLE
LoadRateCalculator -- does it work?

### ISSUE THREAD

**Issue by tggagne** [forcedotcom/dataloader#62] opened 2015-04-13 19:18 UTC
Even though I zeroed-out the number of records to process value to patch #59, I'm bothered that the messages for records-per-second is so off.  At one point during a batch upload it was reporting 600 million records/minute.

I suspect it's dividing the whole of the records processed so far by the duration of the most recent batch--so each subsequent batch reports higher-and-higher rates.

Has anyone else noticed this? Has anyone else looked into the *RateCalculator classes?

**Comment by bigassforce** [comment] 2017-05-20 15:31
We get negative numbers on big loads @tggagne

> [java] 2017-05-20 23:21:23,448 INFO  [execute] progress.NihilistProgressAdapter setSubTask (NihilistProgressAdapter.java:78) - Processed 575,600 of 0 total records.
> Rate: 3,341,109,000 records per hour. Estimated time to complete: 0 minutes and 0 seconds.
> Rate: 24,804,000 records per hour. Estimated time to complete: 0 minutes and 0 seconds.
> Rate: -3,581,000 records per hour. Estimated time to complete: 0 minutes and 0 seconds.
> There are 705,156 successes and 3,444 errors.

**Comment by ashitsalesforce** [comment] 2021-03-02 19:58
It has been a while since the issue was reported. A code review of the current code in LoadRateCalculator.java (calculateSubTask) does not indicate how a negative rate gets generated. Moreover, log messages showing rate are no longer logged, perhaps due to code changes since the issue was filed. Closing it for now. Reopen or report a new one if the issue is still seen.

**Closed by ashitsalesforce** 2021-03-02 19:58 UTC
