### ISSUE TITLE
"Operation not permitted" errors inserting ContentVersion records on an M1 Mac running macOS Monterey version 12.2

### ISSUE THREAD

**Issue by KeithClarke** [forcedotcom/dataloader#553] opened 2022-08-18 09:53 UTC
I have installed the DataLoader (dataloader-53.0.1-uber.jar) from the link in this page https://help.salesforce.com/s/articleView?id=000356287&type=1 and can export data.

But when I try to import ContentVersion records that include paths to the file content, I get the error below in the log where the key line is:
```
Caused by: java.io.FileNotFoundException: /Users/keithclarke/Desktop/Acme Statement 31-12-2021.pdf (Operation not permitted)
```

I've tried adding "java" and the "dataloader.app" into the System Preferences -> Security & Privacy -> Privacy -> Full Disk Access list but that did not help. I realise that this is more about macOS locking down access rights than the DataLoader itself, but if there is a known solution to this problem, it would be great to get it.

Log:
```
2022-08-18 10:32:00,043 INFO  [ModalContext] controller.Controller executeAction (Controller.java:195) - executing operation: insert
2022-08-18 10:32:00,043 INFO  [ModalContext] action.AbstractAction execute (AbstractAction.java:123) - Loading: insert
2022-08-18 10:32:00,078 ERROR [ModalContext] visitor.DAOLoadVisitor visit (DAOLoadVisitor.java:109) - Error converting value to correct data type: /Users/keithclarke/Desktop/Acme Statement 31-12-2021.pdf (Operation not permitted)
org.apache.commons.beanutils.ConversionException: /Users/keithclarke/Desktop/Acme Statement 31-12-2021.pdf (Operation not permitted)
	at com.salesforce.dataloader.dyna.FileByteArrayConverter.convert(FileByteArrayConverter.java:99) ~[dataloader-53.0.1-uber.jar:?]
	at org.apache.commons.beanutils.BeanUtilsBean.convert(BeanUtilsBean.java:1079) ~[dataloader-53.0.1-uber.jar:?]
	at org.apache.commons.beanutils.BeanUtilsBean.convertForCopy(BeanUtilsBean.java:1095) ~[dataloader-53.0.1-uber.jar:?]
	at org.apache.commons.beanutils.BeanUtilsBean.copyProperty(BeanUtilsBean.java:435) ~[dataloader-53.0.1-uber.jar:?]
	at org.apache.commons.beanutils.BeanUtilsBean.copyProperties(BeanUtilsBean.java:268) ~[dataloader-53.0.1-uber.jar:?]
	at org.apache.commons.beanutils.BeanUtils.copyProperties(BeanUtils.java:135) ~[dataloader-53.0.1-uber.jar:?]
	at com.salesforce.dataloader.dyna.SforceDynaBean.convertToDynaBean(SforceDynaBean.java:214) ~[dataloader-53.0.1-uber.jar:?]
	at com.salesforce.dataloader.action.visitor.DAOLoadVisitor.visit(DAOLoadVisitor.java:106) [dataloader-53.0.1-uber.jar:?]
	at com.salesforce.dataloader.action.AbstractLoadAction.visit(AbstractLoadAction.java:89) [dataloader-53.0.1-uber.jar:?]
	at com.salesforce.dataloader.action.AbstractAction.execute(AbstractAction.java:132) [dataloader-53.0.1-uber.jar:?]
	at com.salesforce.dataloader.controller.Controller.executeAction(Controller.java:196) [dataloader-53.0.1-uber.jar:?]
	at com.salesforce.dataloader.ui.SWTLoadRunable.run(SWTLoadRunable.java:58) [dataloader-53.0.1-uber.jar:?]
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122) [dataloader-53.0.1-uber.jar:?]
Caused by: java.io.FileNotFoundException: /Users/keithclarke/Desktop/Acme Statement 31-12-2021.pdf (Operation not permitted)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:111) ~[?:?]
	at com.salesforce.dataloader.dyna.FileByteArrayConverter.convert(FileByteArrayConverter.java:93) ~[dataloader-53.0.1-uber.jar:?]
	... 12 more
```

**Comment by ashitsalesforce** [comment] 2022-08-18 15:44
Hi @KeithClarke , data loader is a Java app. So, identifying the JRE used to run data loader and giving it correct access rights seems to be the way to fix the issue. 

Here is the outline of the fix described at https://stackoverflow.com/questions/41747473/java-io-filenotfoundexception-operation-not-permitted-error-with-keytool-i
    Give Java Full Disk access
    Give Java Files and Folders access to Downloads, Documents and Folders

Your description indicates you gave full disk access to java but perhaps did not give "Files and Folders access to Downloads, Documents, and Folders"? It includes Desktop folder, which is where your pdf resides (see attached screenshot).
<img width="652" alt="Screen Shot 2022-08-18 at 8 42 17 AM" src="https://user-images.githubusercontent.com/71143047/185437609-5b8503e3-fea5-4283-85cc-43724f5fbd72.png">


Also, you may have multiple JREs installed on your desktop. Make sure you give these permissions to the same JRE as the one used by data loader set in DATALOADER_JAVA_HOME or JAVA_HOME environment variable if set. If these are not set then run `which java` command to identify the java used by data loader.

**Comment by ashitsalesforce** [comment] 2022-08-24 03:32
Closing assuming that the issue is resolved.

**Closed by ashitsalesforce** 2022-08-24 03:32 UTC
