### ISSUE TITLE
Should return nonzero status code on error parsing csv

### ISSUE THREAD

**Issue by jsullivanlive** [forcedotcom/dataloader#53] opened 2015-02-05 17:28 UTC
The data loader running via process.bat with an invalid csv file exits with a status code of 0 and prints a javastack trace.  It would be more consistent if a non-zero status code was returned on this error like the one that is returned when you have a classpath error or other types of errors.

**Comment by ashitsalesforce** [comment] 2021-03-02 03:33
Thanks for reporting the issue. This issue will be addressed in v52.

**Closed by ashitsalesforce** 2021-03-02 03:33 UTC

**Comment by kkcrypt** [comment] 2022-09-01 09:32
Hi, [ashitsalesforce](https://github.com/ashitsalesforce)
This issue (The data loader running via process.bat with an invalid csv file exits with a status code of 0 and prints a javastack trace.) is still happening in v55. Could you please take a look?

**Comment by ashitsalesforce** [comment] 2022-09-01 16:10
Hi @kkcrypt , can you provide the command line console output including the stack trace and the error code returned?

**Comment by kkcrypt** [comment] 2022-09-02 09:27
Hi [ashitsalesforce](https://github.com/ashitsalesforce), Thank you for your reply. Please check the following command line console output. The error code is "0" when execute `echo %ERRORLEVEL%` after running process.bat.  

C:\Users\xxx\dataloader\v55.0.1\bin>process.bat
-->
C:\Users\xxx\dataloader\v55.0.1\bin>process.bat "C:\xxx\xxx\dataloader\xxx\xxx" run01
Data Loader requires Java JRE 11 or later. Checking if it is installed...
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2022-09-01 12:08:52,136 INFO  [main] controller.Controller initLog (Controller.java:472) - The log has been initialized
2022-09-01 12:08:52,148 INFO  [main] process.ProcessRunner getInstance (ProcessRunner.java:286) - Initializing process engine
2022-09-01 12:08:52,149 INFO  [main] process.ProcessRunner getInstance (ProcessRunner.java:302) - process.nameis specified in the command line. Loading DynaBean with id run01 from process-conf.xml located in directory C:\Users\xxx\dataloader\xxx\xxx
2022-09-01 12:08:52,156 INFO  [main] process.ProcessConfig getBeanFactory (ProcessConfig.java:105) - Loading process configuration from config file: C:\Users\xxx\dataloader\xxx\xxx\process-conf.xml
2022-09-01 12:08:52,706 INFO  [run01] controller.Controller createDir (Controller.java:325) - Config directory already exists: C:\Users\xxx\dataloader\xxx\xxx
2022-09-01 12:08:52,708 INFO  [run01] controller.Controller initConfig (Controller.java:361) - Looking for file in config path: C:\Users\xxx\dataloader\xxx\xxx\config.properties
2022-09-01 12:08:52,709 INFO  [run01] controller.Controller initConfig (Controller.java:387) - User config is found in C:\Users\xxx\dataloader\xxx\xxx\config.properties
2022-09-01 12:08:52,776 INFO  [run01] controller.Controller initConfig (Controller.java:397) - The controller config has been initialized
2022-09-01 12:08:52,811 INFO  [run01] config.LastRun load (LastRun.java:97) - Last run info will be saved in file: C:\Users\xxx\dataloader\xxx\xxx\run01_lastRun.properties
2022-09-01 12:08:52,817 INFO  [run01] process.ProcessRunner run (ProcessRunner.java:133) - Initializing process engine
2022-09-01 12:08:52,871 INFO  [run01] process.ProcessRunner run (ProcessRunner.java:152) - Logging in to: https://xxx.my.salesforce.com
2022-09-01 12:08:52,887 INFO  [run01] client.PartnerClient login (PartnerClient.java:510) - Beginning Partner Salesforce login ....
[WSC][DataLoaderRunner.main:109]Log file already exists, appending to C:\Users\xxx\dataloader\xxx\xxx\SoapTrace.log
2022-09-01 12:08:53,000 INFO  [run01] client.PartnerClient loginInternal (PartnerClient.java:554) - Salesforce login to https://xxx.my.salesforce.com/services/Soap/u/55.0 as user admin@xxx.com
[WSC][DataLoaderRunner.main:109]Log file already exists, appending to C:\Users\xxx\dataloader\xxx\xxx\SoapTrace.log
2022-09-01 12:08:55,399 INFO  [run01] dao.DataAccessObjectFactory getDaoInstance (DataAccessObjectFactory.java:52) - Instantiating data access object: C:\Users\xxx\dataloader\xxx\xxx\extract.csv of type: csvRead
2022-09-01 12:08:55,405 INFO  [run01] process.ProcessRunner run (ProcessRunner.java:157) - Checking the data access object connection
2022-09-01 12:08:55,410 INFO  [run01] process.ProcessRunner run (ProcessRunner.java:162) - Setting field types
2022-09-01 12:08:55,909 INFO  [run01] process.ProcessRunner run (ProcessRunner.java:166) - Setting object reference types
2022-09-01 12:08:58,077 INFO  [run01] process.ProcessRunner run (ProcessRunner.java:170) - Creating Map
2022-09-01 12:08:58,082 INFO  [run01] action.OperationInfo instantiateAction (OperationInfo.java:87) - Instantiating action for operation: upsert
2022-09-01 12:08:58,139 INFO  [run01] controller.Controller executeAction (Controller.java:188) - executing operation: upsert
2022-09-01 12:08:58,140 INFO  [run01] action.AbstractAction execute (AbstractAction.java:123) - Loading Using Bulk API: upsert
2022-09-01 12:08:58,150 ERROR [run01] util.DAORowUtil calculateTotalRows (DAORowUtil.java:74) - Error Calculating Total Rows
com.salesforce.dataloader.exception.DataAccessObjectException: com.sforce.async.CSVReader$CSVParseException: Not expecting more text after end quote
        at com.salesforce.dataloader.dao.csv.CSVFileReader.readRow(CSVFileReader.java:211) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.util.DAORowUtil.calculateTotalRows(DAORowUtil.java:68) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.dao.csv.CSVFileReader.getTotalRows(CSVFileReader.java:260) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.action.AbstractLoadAction.initOperation(AbstractLoadAction.java:104) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.action.AbstractAction.execute(AbstractAction.java:125) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.controller.Controller.executeAction(Controller.java:189) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:174) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:268) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:252) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:109) ~[dataloader-55.0.1-uber.jar:?]
Caused by: com.sforce.async.CSVReader$CSVParseException: Not expecting more text after end quote
        at com.sforce.async.CSVReader.nextRecordLocal(CSVReader.java:270) ~[dataloader-55.0.1-uber.jar:?]
        at com.sforce.async.CSVReader.nextRecord(CSVReader.java:166) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.dao.csv.CSVFileReader.readRow(CSVFileReader.java:209) ~[dataloader-55.0.1-uber.jar:?]
        ... 9 more
2022-09-01 12:08:58,162 ERROR [run01] action.AbstractAction handleException (AbstractAction.java:223) - Exception occured during loading
com.salesforce.dataloader.exception.DataAccessObjectException: com.sforce.async.CSVReader$CSVParseException: Not expecting more text after end quote
        at com.salesforce.dataloader.dao.csv.CSVFileReader.readRow(CSVFileReader.java:211) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.util.DAORowUtil.calculateTotalRows(DAORowUtil.java:68) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.dao.csv.CSVFileReader.getTotalRows(CSVFileReader.java:260) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.action.AbstractLoadAction.initOperation(AbstractLoadAction.java:104) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.action.AbstractAction.execute(AbstractAction.java:125) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.controller.Controller.executeAction(Controller.java:189) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:174) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:268) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:252) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:109) ~[dataloader-55.0.1-uber.jar:?]
Caused by: com.sforce.async.CSVReader$CSVParseException: Not expecting more text after end quote
        at com.sforce.async.CSVReader.nextRecordLocal(CSVReader.java:270) ~[dataloader-55.0.1-uber.jar:?]
        at com.sforce.async.CSVReader.nextRecord(CSVReader.java:166) ~[dataloader-55.0.1-uber.jar:?]
        at com.salesforce.dataloader.dao.csv.CSVFileReader.readRow(CSVFileReader.java:209) ~[dataloader-55.0.1-uber.jar:?]
        ... 9 more
2022-09-01 12:08:58,164 ERROR [run01] progress.NihilistProgressAdapter doneError (NihilistProgressAdapter.java:58) - com.sforce.async.CSVReader$CSVParseException: Not expecting more text after end quote

C:\Users\xxx\dataloader\v55.0.1\bin>echo %ERRORLEVEL%
-->
0

**Comment by ashitsalesforce** [comment] 2022-09-02 20:13
Hi @kkcrypt , thanks for sharing the output. The fix provided since data loader v52 is that if for some reason (such as incorrect id of the batch process bean) the java code exited with non-zero error code whereas the invoking process.bat would exit with a zero error code.

The issue you are encountering is somewhat different: the java code is exiting with a zero error code when it encounters text after end of quote, which in turn results in a zero error code returned by the batch script. We are looking into fixing that.

**Comment by kkcrypt** [comment] 2022-09-05 02:10
Hi @ashitsalesforce , Thank you so much for your help!

**Comment by kkcrypt** [comment] 2022-09-05 06:49
Hi @ashitsalesforce, sorry to bother you again. Just for confirmation, my understanding is the https://github.com/forcedotcom/dataloader/issues/53#issuecomment-1235277186 will be fixed in v56.0.3 via pull request of https://github.com/forcedotcom/dataloader/pull/559, is that right? If my understanding is right can I ask you when will the v56.0.3 be released?

**Comment by ashitsalesforce** [comment] 2022-09-06 05:33
Hi @kkcrypt , your understanding is right that the issue will be fixed in v56.0.3 and later releases. As to when the next release will be is under discussion. We usually do a patch release when there are one or more critical bugs whose fix cannot await the next major release.

**Comment by ashitsalesforce** [comment] 2022-09-07 00:08
Hi @kkcrypt , v56.0.3 is available for download [here](https://github.com/forcedotcom/dataloader/releases/tag/v56.0.3).

**Comment by kkcrypt** [comment] 2022-09-07 02:07
Hi @ashitsalesforce, many thanks for your information!
