### ISSUE TITLE
dataloader cli - Error opening file writer for file: access denied issue

### ISSUE THREAD

**Issue by srinirwork** [forcedotcom/dataloader#954] opened 2024-01-21 16:13 UTC
I was trying to insert accounts using data loader cli, but I get access denied error even though there are read, write and execute permissions to the status folder. Infact, I am able to create a text file in status folder manually. Here is the dataloader console log. Any help is appreciated.

C:\Users\srini>process.bat C:\dataloader\dataload\accounts\config accountInsert
Data Loader requires Java JRE 11 or later. Checking if it is installed...
2024-01-21 09:57:10,121 INFO [main] process.ProcessRunner getInstance (ProcessRunner.java:288) - Initializing process engine
2024-01-21 09:57:10,121 INFO [main] process.ProcessRunner getInstance (ProcessRunner.java:303) - process.nameis specified in the command line. Loading DynaBean with id accountInsert from process-conf.xml located in folder C:\dataloader\dataload\accounts\config
2024-01-21 09:57:10,121 INFO [main] process.ProcessConfig getBeanFactory (ProcessConfig.java:106) - Loading process configuration from config file: C:\dataloader\dataload\accounts\config\process-conf.xml
2024-01-21 09:57:10,279 INFO [accountInsert] config.Config createDir (Config.java:1485) - Config folder already exists: C:\dataloader\dataload\accounts\config
2024-01-21 09:57:10,279 INFO [accountInsert] config.Config getInstance (Config.java:1518) - Looking for file in config path: C:\dataloader\dataload\accounts\config\config.properties
2024-01-21 09:57:10,327 INFO [accountInsert] config.LastRun load (LastRun.java:87) - Last run info will be saved in file: C:\dataloader\dataload\accounts\config\insert_lastRun.properties
2024-01-21 09:57:10,343 INFO [accountInsert] config.Config getInstance (Config.java:1555) - The controller config has been initialized
2024-01-21 09:57:10,343 INFO [accountInsert] process.ProcessRunner run (ProcessRunner.java:135) - Initializing process engine
2024-01-21 09:57:10,343 INFO [accountInsert] process.ProcessRunner run (ProcessRunner.java:155) - Logging in to: https://test.salesforce.com/
2024-01-21 09:57:10,343 INFO [accountInsert] client.PartnerClient login (PartnerClient.java:548) - Beginning Partner Salesforce login ....
2024-01-21 09:57:10,374 INFO [accountInsert] client.PartnerClient loginInternal (PartnerClient.java:603) - Salesforce login to https://test.salesforce.com/services/Soap/u/58.0/ as user XXXXXXXXX
2024-01-21 09:57:11,611 INFO [accountInsert] process.ProcessRunner run (ProcessRunner.java:158) - Setting field types
2024-01-21 09:57:12,803 INFO [accountInsert] process.ProcessRunner run (ProcessRunner.java:162) - Setting object reference types
2024-01-21 09:57:15,847 INFO [accountInsert] process.ProcessRunner run (ProcessRunner.java:166) - Creating Map
2024-01-21 09:57:15,847 INFO [accountInsert] dao.DataAccessObjectFactory getDaoInstance (DataAccessObjectFactory.java:55) - Instantiating data access object: C:\dataloader\dataload\accounts\data\account_data.csv of type: csvRead
2024-01-21 09:57:15,854 INFO [accountInsert] controller.Controller createDao (Controller.java:238) - Checking the data access object connection
2024-01-21 09:57:15,933 INFO [accountInsert] csv.CSVFileReader readHeaderRow (CSVFileReader.java:250) - Columns in CSV header = 2
2024-01-21 09:57:15,949 INFO [accountInsert] action.OperationInfo instantiateAction (OperationInfo.java:87) - Instantiating action for operation: insert
2024-01-21 09:57:15,965 INFO [accountInsert] csv.CSVFileReader readHeaderRow (CSVFileReader.java:250) - Columns in CSV header = 2
2024-01-21 09:57:15,981 INFO [accountInsert] csv.CSVFileReader readHeaderRow (CSVFileReader.java:250) - Columns in CSV header = 2
2024-01-21 09:57:15,981 INFO [accountInsert] controller.Controller executeAction (Controller.java:141) - executing operation: insert
2024-01-21 09:57:15,981 INFO [accountInsert] action.AbstractAction execute (AbstractAction.java:124) - Loading: insert
2024-01-21 09:57:15,981 INFO [accountInsert] csv.CSVFileReader readHeaderRow (CSVFileReader.java:250) - Columns in CSV header = 2
2024-01-21 09:57:15,997 ERROR [accountInsert] csv.CSVFileWriter open (CSVFileWriter.java:119) - Error opening file writer for file: C:\dataloader\dataload\accounts\status
java.io.FileNotFoundException: C:\dataloader\dataload\accounts\status (Access is denied)
at java.io.FileOutputStream.open0(Native Method) ~[?:?]
at java.io.FileOutputStream.open(FileOutputStream.java:289) ~[?:?]
at java.io.FileOutputStream.(FileOutputStream.java:230) ~[?:?]
at java.io.FileOutputStream.(FileOutputStream.java:118) ~[?:?]
at com.salesforce.dataloader.dao.csv.CSVFileWriter.open(CSVFileWriter.java:111) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.action.AbstractAction.openSuccessWriter(AbstractAction.java:291) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.action.AbstractAction.execute(AbstractAction.java:129) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.controller.Controller.executeAction(Controller.java:143) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:171) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:259) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:101) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:83) [dataloader-58.0.4.jar:?]
2024-01-21 09:57:16,003 ERROR [accountInsert] action.AbstractAction handleException (AbstractAction.java:224) - Exception occured during loading
com.salesforce.dataloader.exception.LoadException: Error opening success status file: C:\dataloader\dataload\accounts\status
at com.salesforce.dataloader.action.AbstractAction.openSuccessWriter(AbstractAction.java:295) ~[dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.action.AbstractAction.execute(AbstractAction.java:129) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.controller.Controller.executeAction(Controller.java:143) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:171) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:259) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:101) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:83) [dataloader-58.0.4.jar:?]
Caused by: com.salesforce.dataloader.exception.DataAccessObjectInitializationException: Error opening file writer for file: C:\dataloader\dataload\accounts\status
at com.salesforce.dataloader.dao.csv.CSVFileWriter.open(CSVFileWriter.java:120) ~[dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.action.AbstractAction.openSuccessWriter(AbstractAction.java:291) ~[dataloader-58.0.4.jar:?]
... 6 more
Caused by: java.io.FileNotFoundException: C:\dataloader\dataload\accounts\status (Access is denied)
at java.io.FileOutputStream.open0(Native Method) ~[?:?]
at java.io.FileOutputStream.open(FileOutputStream.java:289) ~[?:?]
at java.io.FileOutputStream.(FileOutputStream.java:230) ~[?:?]
at java.io.FileOutputStream.(FileOutputStream.java:118) ~[?:?]
at com.salesforce.dataloader.dao.csv.CSVFileWriter.open(CSVFileWriter.java:111) ~[dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.action.AbstractAction.openSuccessWriter(AbstractAction.java:291) ~[dataloader-58.0.4.jar:?]
... 6 more
2024-01-21 09:57:16,003 ERROR [accountInsert] progress.NihilistProgressAdapter doneError (NihilistProgressAdapter.java:62) - Error opening success status file: C:\dataloader\dataload\accounts\status
Error opening success status file: C:\dataloader\dataload\accounts\status
2024-01-21 09:57:16,003 FATAL [main] process.ProcessRunner logErrorAndExitProcess (ProcessRunner.java:244) - Unable to run process
java.lang.RuntimeException: Error opening success status file: C:\dataloader\dataload\accounts\status
at com.salesforce.dataloader.process.ProcessRunner.logErrorAndExitProcess(ProcessRunner.java:242) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:262) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:101) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:83) [dataloader-58.0.4.jar:?]
2024-01-21 09:57:16,003 FATAL [main] process.ProcessRunner logErrorAndExitProcess (ProcessRunner.java:244) - Unable to run process
java.lang.RuntimeException: Error opening success status file: C:\dataloader\dataload\accounts\status
at com.salesforce.dataloader.process.ProcessRunner.logErrorAndExitProcess(ProcessRunner.java:245) ~[dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:101) [dataloader-58.0.4.jar:?]
at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:83) [dataloader-58.0.4.jar:?]
Exception in thread "main" java.lang.RuntimeException: Error opening success status file: C:\dataloader\dataload\accounts\status
at com.salesforce.dataloader.process.ProcessRunner.logErrorAndExitProcess(ProcessRunner.java:245)
at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:103)
at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:83)

C:\Users\srini>

**Comment by ashitsalesforce** [comment] 2024-01-21 17:02
Hi @srinirwork, 

Can you provide process bean settings in process-conf.xml file, specifically success and error properties? These should be specified along the lines of:
```
...
                <entry key="process.outputSuccess"
                    value=.../>
                <entry key="process.outputError"
                    value=.../>
...
```

**Comment by ashitsalesforce** [comment] 2024-01-21 17:07
Closing it as it is a duplicate of #955 which is resolved.

**Closed by ashitsalesforce** 2024-01-21 17:07 UTC
