### ISSUE TITLE
Silent failure on certain malformed CSV

### ISSUE THREAD

**Issue by camisotro** [forcedotcom/dataloader#127] opened 2017-01-09 14:54 UTC
I had an issue where, for reasons related to my extract/transform script, certain fields in a CSV file terminated in a carriage return (CR) without line feed (LF), and my transform script failed to escape those fields with quotes. When I tried loading this CSV file into Data Loader, it failed to produce an error message but also wouldn't allow me to continue any further in the wizard, getting stuck on the Initializing popup. I noticed most other malformed CSV files result in errors.

Actually it turns out this error also occurs with full CRLF before comma. But this is how I first ran into it.

**Comment by xbiansf** [comment] 2017-01-10 01:01
Thanks for reporting this issue.  This is related to the csv parsing logic in Dataloader. I created an internal case for this issue to get team's attention.  At the same time, please remove the <CR> which caused the CSV parser.

**Comment by ashitsalesforce** [comment] 2021-02-27 17:28
The issue is addressed in v51 of Data Loader. It generates an error that the row with the CR has missing data   and does not let the user proceed to the next step.

**Closed by ashitsalesforce** 2021-02-27 17:28 UTC
