### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by kudohs** [forcedotcom/dataloader#141] opened 2017-07-05 16:50 UTC
Finally, I was able to open up GUI with following command:
java -jar target/dataloader-**40.0.0**-uber.jar
Not
java -jar target/dataloader-**40.0**-uber.jar
It appears that there is an error with **40.0** rather than **40.0.0**.

I am not able to login thru my username and password to https://login.salesforce.com.
It says: "Error: Check your username and password, If you still can't log in, contact"

When I looked at Login history from Org ->Set up -> My Setting -> Login History, error message says, "**Failed: API security token required**"

What do I need to do?

**Comment by brytonpilling** [comment] 2017-09-28 11:45
Have you generated a security token in your org and appended this to your password in dataloader?

**Comment by ashitsalesforce** [comment] 2021-02-24 16:56
Closing as the issue is likely solved.

**Closed by ashitsalesforce** 2021-02-24 16:56 UTC
