### ISSUE TITLE
Functions like Format and ConvertCurrency and not working in the Dataloader CLI

### ISSUE THREAD

**Issue by ImranMoTown** [forcedotcom/dataloader#1203] opened 2024-07-31 18:28 UTC
When using the Dataloader CLI I'm finding that the FORMAT and CurrencyConvert functions are returning blanks when applied to a field of type currency.  When running the SOQL through developer console, I'm finding the correct results are returned.  Examples include:

SELECT 
	id, 
	FORMAT(AnnualRevenue)
FROM Account
WHERE AnnualRevenue!=NULL

SELECT 
	id, 
	convertCurrency(AnnualRevenue)
FROM Account

These are outputting csv files that look like this:
"id","convertCurrency(AnnualRevenue)"
"0010g00001XiGDHAA3",""
"0010g00001XiGDWAA3",""
"0010g00001XiGHTAA3",""
"0010g00001XiGHYAA3",""
"0010g00001XiGHdAAN",""

I am using version v61.1.0

**Comment by ashitsalesforce** [comment] 2024-07-31 19:53
Hi @ImranMoTown , uncheck the checkbox `"Limit query result fields to the fields specified in the SOQL query"` in Settings dialog and try. 
<img width="980" alt="Screenshot 2024-07-31 at 12 48 31 PM" src="https://github.com/user-attachments/assets/462cba9e-a18a-4771-83b4-3d3a038f0fe5">

**Comment by ImranMoTown** [comment] 2024-07-31 20:25
Hi, I'm using the Command Line is there a property I should set in the
process-conf file?

**Comment by ashitsalesforce** [comment] 2024-07-31 20:29
set `loader.query.limitOutputToQueryFields=false`.

**Comment by ImranMoTown** [comment] 2024-08-01 12:55
Thanks!
Yes this did help, it does return the results of the functions now.  There
are some other consequences however:
1) A "type" column has been added which I think I can handle.
2) The columns are put in alpha order instead of the order in the SELECT
stmt, this is a big issue for the platform and process I have built around
using DataLoader.  Is it possible to leave them in the order of the SOQL
select and add the type column to beginning or end?

This limitOutputToQueryFields setting is not documented anywhere that I can
find, can you provide any more info around what it does?

**Comment by ashitsalesforce** [comment] 2024-08-01 15:38
`limitOutputToQueryFields` was introduced recently to skip client-side processing done by data loader before sending SOQL query to the server. Regarding alphabetical order of results and appearance of "type" column, these are due to data loader saving server results, including column names as-is when `limitOutputToQueryFields=false`. 

This is clearly a limitation. Let's keep the issue open so that we can look into ways to address it.

**Comment by ashitsalesforce** [comment] 2024-08-01 20:11
Hi @ImranMoTown , I am attaching data loader with fix below for you to try. If it works, you can use format() function to also address issue #1204.
[dataloader_v62.0.0.zip](https://github.com/user-attachments/files/16461473/dataloader_v62.0.0.zip)

MD5 (dataloader_v62.0.0.zip) = 0c3c9a915c346d5abb782d3a5521d96d

**Comment by ImranMoTown** [comment] 2024-08-05 22:54
Thank-you @ashitsalesforce,
I tried v62, I'm not sure what it is supposed fix, I still see the type column and the output columns are still in alpha order instead of the Select list order.  There is also a login exception, something about the API version but then it still works.   I've worked around both these issues so it's not a big deal.  I will say the "type" column is probably a broader issue, for now I've added the column to all my ETL tables but the Account object, for example, has standard field called "Type" (with a capital) so that caused an issue I needed to work around as well.  If the field needs to be in the export, you might want to rename it to ObjectType or something.

**Comment by ashitsalesforce** [comment] 2024-08-05 23:16
Hi @ImranMoTown , the fixed version works when you set `limitOutputToQueryFields=true`. That way you can go with the column order in SOQL Select clause. 

API version exception occurs because the new version first tries v62.0 (Winter '24 release) API , which is not deployed to any production yet but coming soon (in next couple of months). When it fails, it switches to v61.0 and continues. In other words, it is harmless and you can ignore it.

**Comment by ImranMoTown** [comment] 2024-08-06 15:54
Oh, I got you now, I thought the fixed version ordered the columns while still setting limitOutputToQueryFields=false so it was still returning the extra fields like "type" and in alpha order in my testing.  v62 works great in my testing so far.  FORMAT a currency field is returning numbers without scientific notation and doing the currency conversion.  The columns are also returned in the order of the SOQL.  Again, very much appreciate your help as always.

**Comment by ashitsalesforce** [comment] 2024-08-06 15:57
Hi @ImranMoTown , good to hear that your issue is addressed. Thanks for reporting it with the needed specifics so that we can reproduce and fix it quickly. I am closing this one and #1204 given your response.

**Closed by ashitsalesforce** 2024-08-06 15:57 UTC
