### ISSUE TITLE
Data Loader running from .bat fails to open

### ISSUE THREAD

**Issue by WKingCIP** [forcedotcom/dataloader#483] opened 2022-06-09 21:51 UTC
Environment: 
Windows 10 
Amazon Corretto v11.0.15_9

Issue;
When running the Data Loader from the dataload.bat file, the data loader never opens.  When run from command line, the data loader bat file will throw the following error and terminate. 
![Snag_60d704](https://user-images.githubusercontent.com/104395774/172951228-8fec71c6-5ac8-48f2-aeb3-10b8b43d86b7.png)

Workaround:
Opening the dataloader-55.0.1-uber.jar file directly will open the application.

**Comment by ashitsalesforce** [comment] 2022-06-09 22:50
Hi @WKingCIP , 

Change the first line of dataloader.bat from `@echo off` to `@echo on`, run dataloader.bat, capture its output, and share so that we can troubleshoot the issue further.

**Comment by WKingCIP** [comment] 2022-06-10 13:06
C:\dataloader\v55.0.1>dataloader.bat

C:\dataloader\v55.0.1>setlocal

C:\dataloader\v55.0.1>set DATALOADER_VERSION=55.0.1

C:\dataloader\v55.0.1>for /F "tokens=1 delims=." %a in ("55.0.1") do (set DATALOADER_SHORT_VERSION=%a )

C:\dataloader\v55.0.1>(set DATALOADER_SHORT_VERSION=55 )

C:\dataloader\v55.0.1>set DATALOADER_UBER_JAR_NAME=C:\dataloader\v55.0.1\\dataloader-55.0.1-uber.jar

C:\dataloader\v55.0.1>set MIN_JAVA_VERSION=11

C:\dataloader\v55.0.1>IF NOT "" == "" (IF "" == "-skipbanner" (
SHIFT
 GOTO AFTER_BANNER
) )

C:\dataloader\v55.0.1>echo.


C:\dataloader\v55.0.1>echo *************************************************************************
*************************************************************************

C:\dataloader\v55.0.1>echo **            ___  ____ ___ ____   _    ____ ____ ___  ____ ____       **
**            ___  ____ ___ ____   _    ____ ____ ___  ____ ____       **

C:\dataloader\v55.0.1>echo **            |  \ |__|  |  |__|   |    |  | |__| |  \ |___ |__/       **
**            |  \ |__|  |  |__|   |    |  | |__| |  \ |___ |__/       **

C:\dataloader\v55.0.1>echo **            |__/ |  |  |  |  |   |___ |__| |  | |__/ |___ |  \       **
**            |__/ |  |  |  |  |   |___ |__| |  | |__/ |___ |  \       **

C:\dataloader\v55.0.1>echo **                                                                     **
**                                                                     **

C:\dataloader\v55.0.1>echo **  Data Loader v55 is a Salesforce supported Open Source project to   **
**  Data Loader v55 is a Salesforce supported Open Source project to   **

C:\dataloader\v55.0.1>echo **  help you import data to and export data from your Salesforce org.  **
**  help you import data to and export data from your Salesforce org.  **

C:\dataloader\v55.0.1>echo **  It requires Java JRE 11 or later to run.                           **
**  It requires Java JRE 11 or later to run.                           **

C:\dataloader\v55.0.1>echo **                                                                     **
**                                                                     **

C:\dataloader\v55.0.1>echo **  Github Project Url:                                                **
**  Github Project Url:                                                **

C:\dataloader\v55.0.1>echo **       https://github.com/forcedotcom/dataloader                     **
**       https://github.com/forcedotcom/dataloader                     **

C:\dataloader\v55.0.1>echo **  Salesforce Documentation:                                          **
**  Salesforce Documentation:                                          **

C:\dataloader\v55.0.1>echo **       https://help.salesforce.com/articleView?id=data_loader.htm    **
**       https://help.salesforce.com/articleView?id=data_loader.htm    **

C:\dataloader\v55.0.1>echo **                                                                     **
**                                                                     **

C:\dataloader\v55.0.1>echo *************************************************************************
*************************************************************************

C:\dataloader\v55.0.1>echo.


C:\dataloader\v55.0.1>IF NOT "" == "" (set JAVA_HOME="" )

C:\dataloader\v55.0.1>echo Data Loader requires Java JRE 11 or later. Checking if it is installed...
Data Loader requires Java JRE 11 or later. Checking if it is installed...

C:\dataloader\v55.0.1>PATH="C:\Program Files\Amazon Corretto\jdk11.0.15_9"\bin\;C:\Program Files\Amazon Corretto\jdk11.0.15_9\bin;C:\Program Files\Amazon Corretto\jdk1.8.0_292\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\wking\AppData\Local\Microsoft\WindowsApps;;

C:\dataloader\v55.0.1>java -version   1>nul 2>nul  || (goto NoJavaErrorExit )

C:\dataloader\v55.0.1>for /F "tokens=3" %a in ('java -version 2>&1 | findstr /i "version"') do (set JAVA_FULL_VERSION=%a )

C:\dataloader\v55.0.1>(set JAVA_FULL_VERSION="11.0.15" )

C:\dataloader\v55.0.1>set JAVA_FULL_VERSION=11.0.15

C:\dataloader\v55.0.1>for /F "tokens=1 delims=." %m in ("11.0.15") do (set /A JAVA_MAJOR_VERSION=%m )

C:\dataloader\v55.0.1>(set /A JAVA_MAJOR_VERSION=11 )

C:\dataloader\v55.0.1>if 11 LSS 11 (goto JavaVersionErrorExit )

C:\dataloader\v55.0.1>java -jar C:\dataloader\v55.0.1\\dataloader-55.0.1-uber.jar
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2022-06-10 08:00:49,158 INFO  [main] controller.Controller initLog (Controller.java:472) - The log has been initialized
Error: Could not find or load main class Files\Amazon
Caused by: java.lang.ClassNotFoundException: Files\Amazon

C:\dataloader\v55.0.1>goto SuccessExit

C:\dataloader\v55.0.1>endlocal

C:\dataloader\v55.0.1>exit /b 0

C:\dataloader\v55.0.1>

**Comment by ashitsalesforce** [comment] 2022-06-10 15:29
Hi @WKingCIP , there is a bug in the way data loader handles space character (' ') in JAVA_HOME environment variable. The workaround for now is to set another environment variable, DATALOADER_JAVA_HOME with the value %JAVA_HOME%.

**Comment by ashitsalesforce** [comment] 2022-06-14 03:03
Closing this assuming that the issue is addressed with the suggested workaround.

**Closed by ashitsalesforce** 2022-06-14 03:03 UTC

**Comment by rjohnson06gh** [comment] 2022-06-23 21:13
From my testing today and in reviewing version 54.0.0, the PATH variable is different, and it appears it's trying to form the path backwards, which is why it's giving that error (you see it more clearly if you try and use the Azul JDK). In version 54, the PATH is set like: PATH=%PATH%;%JAVA_HOME%\bin\;

In version 55.0.1, it gets set like this: PATH="%JAVA_HOME%"\bin\;%PATH%;.

I set the path the same in version 55.0.1 as it was in 54.0.0 and it opens correctly, no workaround needed (but that's good to know).

**Comment by ashitsalesforce** [comment] 2022-06-23 21:28
Hi @rjohnson06gh , not sure what is the value of the env variable PATH on your desktop and why it causes an issue with 55.0.1. Note that the latest setting of PATH in dataloader.bat (changed after the release of 55.0.1) is:

`    PATH=%JAVA_HOME%\bin\;%PATH%;`

If you don't mind trying it out and let us know if it works or if there are any issues. If there is an issue, we would like to hear more details of the issue to see if we can address it in the future releases.

Thanks.

**Comment by ashitsalesforce** [comment] 2022-06-24 14:53
Yes, it will be. Here is the relevant code snippet from the latest dataloader.bat:
```
...
...
:AFTER_BANNER
 
IF NOT "%DATALOADER_JAVA_HOME%" == "" (
    set JAVA_HOME=%DATALOADER_JAVA_HOME%
)

:CheckMinJRE
    echo Data Loader requires Java JRE %MIN_JAVA_VERSION% or later. Checking if it is installed...

    PATH=%JAVA_HOME%\bin\;%PATH%;
...
...
```
